#!/usr/bin/env python3
"""PORTING-LADDER.md — the forensic-port hierarchy (generated from the claim-ladder + coverage map).

Not marketing. A hard map: every GnuCOBOL court/surface sits at exactly one level, so 'we are climbing the
GnuCOBOL semantic stack' is legible and not 'a random pile of courts'. The gate fails if a GNURUST/atlas
court is unplaced or the doc is stale.

  run.py generate | check
"""
import json, os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

LEVELS = [
 (0, "refused subsystem", "out of the data-evidence lane; refused with negative capabilities, never guessed"),
 (1, "observed atlas", "behavior is recorded as observed evidence (a sweep), not a pure-kernel implementation"),
 (2, "byte-equivalent helper", "a pure Rust function reproduces a storage/field/representation byte result"),
 (3, "statement byte court", "a Procedure-Division statement's receiver bytes are reproduced byte-for-byte"),
 (4, "file/runtime-status court", "file/runtime status observation bound to declared conditions"),
 (5, "control-flow fragment", "control-flow surface OBSERVED as an atlas; execution is not claimed"),
 (6, "program-execution slice", "executing a program slice end-to-end (not yet started)"),
 (7, "compiler/runtime replacement", "NOT CLAIMED — gnucobol-rs is a compatibility court, not a compiler"),
]
# declared placement of each GNURUST/atlas court (cross-checked against the claim-ladder)
PLACE = {
 2:["GNURUST.2","GNURUST.3","GNURUST.4","GNURUST.5","GNURUST.6","GNURUST.8","GNURUST.9","GNURUST.10",
    "GNURUST.11","GNURUST.INTRINSIC.LENGTH.1","GNURUST.INTRINSIC.NUMVAL.1","GNURUST.INTRINSIC.NUMVAL-C.1","GNURUST.INTRINSIC.MOD-REM.1","GNURUST.INTRINSIC.INTEGER.1","GNURUST.INTRINSIC.CASE.1","GNURUST.INTRINSIC.ORD-CHAR.1","GNURUST.14","GNURUST.15","GNURUST.16","GNURUST.17","GNURUST.18"],
 3:["GNURUST.7","GNURUST.13","GNURUST.19","GNURUST.REMAINDER.1","GNURUST.FILE.SEQUENTIAL.1",
    "GNURUST.12","GNURUST.INITIALIZE.1","GNURUST.INSPECT.1","GNURUST.STRING.UNSTRING.1","GNURUST.ACCEPT.DISPLAY.1","GNURUST.ACCEPT.DISPLAY.2"],
 1:["SIZE.ERROR.ATLAS.1","GNURUST.INTRINSIC.ATLAS.1"],
 4:["GNURUST.FILE.STATUS.1"],
 5:["GNURUST.PROCEDURE.FLOW.ATLAS.1"],
}

def claim_ids():
    return {c["id"] for c in json.load(open(os.path.join(ROOT,"reports/claim-ladder.json")))["courts"]}
def gnucobol_courts():
    return {c for c in claim_ids() if c.startswith("GNURUST.") or "ATLAS" in c} - {"GNURUST.COVERAGE.1"}
def coverage():
    return json.load(open(os.path.join(ROOT,"reports/gnurust-coverage.json")))

def build():
    cov = coverage()
    placed = {cid: lvl for lvl, ids in PLACE.items() for cid in ids}
    rows = []
    for (lvl, name, desc) in LEVELS:
        courts = sorted([c for c in placed if placed[c] == lvl])
        rows.append({"level": lvl, "name": name, "description": desc, "courts": courts})
    return {"schema":"gnurust-porting-ladder-v1","court":"PORTING-LADDER",
            "placed": placed, "levels": rows,
            "coverage_status_counts": cov["status_counts"],
            "downstream":"KOBOLD (kobold-data-shim) composes the sealed gnucobol-rs courts into a fixed-record migration-evidence layer; it adds no semantics a lower court has not sealed.",
            "non_claims":["NEG.LADDER.LEVEL_NOT_QUALITY","NEG.LADDER.NOT_A_COMPLETENESS_CLAIM","NEG.LADDER.NO_NEW_TRUTH"]}

def render_md(b):
    cc = b["coverage_status_counts"]
    L = ["<!-- generated by lab/ladder/run.py — do not edit by hand -->","",
         "# PORTING-LADDER — the forensic GnuCOBOL port hierarchy","",
         "> [!IMPORTANT]","> Not marketing. A hard map of where each admitted GnuCOBOL surface sits. We are not adding random "
         "courts — we are climbing the GnuCOBOL semantic stack, level by level, with oracle receipts.","",
         f"Coverage frontier (from `GNURUST.COVERAGE.1`): **sealed {cc['sealed']}**, observed {cc['observed']}, "
         f"refused {cc['negative']}, **missing {cc['missing']}**.","",
         "| level | meaning | courts |","|:---:|---|---|"]
    for r in b["levels"]:
        courts = ", ".join(f"`{c}`" for c in r["courts"]) if r["courts"] else "—"
        L.append(f"| **{r['level']}** | {r['name']} — {r['description']} | {courts} |")
    L += ["","## Downstream composition","",b["downstream"],"",
          "## Non-claims","> The level number is **evidence shape, not quality**; the ladder is **not a completeness claim** "
          "(see the missing surfaces in `GNURUST.COVERAGE.1`); it creates **no new truth**.",""]
    return "\n".join(L)+"\n"

def generate():
    b=build(); json.dump(b,open(os.path.join(ROOT,"reports/porting-ladder.json"),"w"),indent=2)
    open(os.path.join(ROOT,"PORTING-LADDER.md"),"w").write(render_md(b)); print("PORTING-LADDER.md generated")

def check():
    bad=0
    if not os.path.exists(os.path.join(ROOT,"PORTING-LADDER.md")):
        print("GATE: PORTING-LADDER.md missing"); return 1
    fresh=build()
    # every GNURUST/atlas court is placed at exactly one level
    placed=set(fresh["placed"]); allc=gnucobol_courts()
    for c in sorted(allc-placed): print(f"GATE: court {c} is not placed on the porting ladder"); bad+=1
    for c in sorted(placed-allc): print(f"GATE: ladder places {c} which is not a claim-ladder court"); bad+=1
    if open(os.path.join(ROOT,"PORTING-LADDER.md")).read()!=render_md(fresh): print("GATE: PORTING-LADDER.md != regenerated"); bad+=1
    if bad: print(f"!! {bad} PORTING-LADDER finding(s)"); return 1
    print(f"PORTING-LADDER: {len(placed)} courts placed across {len(LEVELS)} levels; fresh"); return 0

if __name__=="__main__":
    cmd=sys.argv[1] if len(sys.argv)>1 else "check"
    {"generate":generate,"check":lambda: sys.exit(check())}.get(cmd, lambda: sys.exit("usage: generate|check"))()
