//! The parity joiner — the typed replacement for grep name-matching. It consumes the libcob C symbol
//! index (with preprocessor status) and the Rust symbol index (real `fn`s vs doc-only mentions) and emits
//! the per-function verdict + the stronger per-file scoreboard. A C function is only "ported" when a real
//! Rust `fn` of that name exists; a name that appears solely in a doc comment is reported as a `doc_only`
//! false hit, not a port.

use crate::libcob_symbols;
use crate::model::{ParityFn, ParityRow, PreprocStatus, RustStatus};
use crate::rust_symbols::{self, RustIndex};
use crate::paths;
use serde_json::{json, Value};
use std::collections::BTreeMap;
use std::path::Path;

/// Build the per-file parity rows from the two indexes.
pub fn build_rows(root: &Path) -> Option<(Vec<ParityRow>, RustIndex)> {
    let c_syms = libcob_symbols::index_all(root)?;
    let rust = rust_symbols::index(root);

    // group C symbols by file, preserving the canonical file order.
    let mut by_file: BTreeMap<&str, Vec<&crate::model::LibcobSymbol>> = BTreeMap::new();
    for s in &c_syms {
        by_file.entry(s.file.as_str()).or_default().push(s);
    }

    let mut rows = Vec::new();
    for f in paths::FILES {
        let syms = by_file.remove(f).unwrap_or_default();
        let mut fns = Vec::new();
        let (mut compiled, mut disabled) = (0usize, 0usize);
        let (mut active, mut inactive, mut testonly, mut doc, mut missing) = (0, 0, 0, 0, 0);
        let mut gap = Vec::new();
        let mut compiled_ok = 0usize;

        for s in &syms {
            let rust_status;
            let mut rust_module = None;
            match rust.defs.get(&s.function) {
                Some(sym) => {
                    rust_status = sym.status;
                    rust_module = Some(sym.module.clone());
                }
                None => {
                    rust_status = if rust.all_tokens.contains(&s.function) {
                        RustStatus::DocOnly
                    } else {
                        RustStatus::Missing
                    };
                }
            }
            match rust_status {
                RustStatus::Active => active += 1,
                RustStatus::InactiveMirror => inactive += 1,
                RustStatus::TestOnly => testonly += 1,
                RustStatus::DocOnly => doc += 1,
                RustStatus::Missing => missing += 1,
            }
            let has_real_fn = matches!(
                rust_status,
                RustStatus::Active | RustStatus::InactiveMirror | RustStatus::TestOnly
            );
            match s.preprocessor_status {
                PreprocStatus::Compiled => {
                    compiled += 1;
                    if has_real_fn {
                        compiled_ok += 1;
                    } else {
                        gap.push(s.function.clone());
                    }
                }
                _ => {
                    disabled += 1;
                    if !has_real_fn {
                        // a disabled-source mirror with no Rust counterpart — tracked, lower priority.
                    }
                }
            }
            fns.push(ParityFn {
                function: s.function.clone(),
                preprocessor_status: s.preprocessor_status,
                rust_status,
                rust_module,
            });
        }

        let source_funcs = syms.len();
        let compiled_parity_pct = if compiled > 0 {
            (compiled_ok as f64) * 1000.0 / (compiled as f64)
        } else {
            1000.0
        };
        gap.sort();
        gap.dedup();
        rows.push(ParityRow {
            file: f.to_string(),
            source_funcs,
            compiled,
            disabled,
            active_ported: active,
            inactive_mirrors: inactive,
            test_only: testonly,
            doc_only: doc,
            missing,
            gap,
            compiled_parity_pct: compiled_parity_pct.round() / 10.0,
            fns,
        });
    }
    Some((rows, rust))
}

/// Render the human scoreboard (`LIBCOB-PARITY.md`).
pub fn render_md(rows: &[ParityRow]) -> String {
    let mut l = vec![
        "<!-- generated by `cargo run -p gnucobol-rs-port-index -- parity` — do not edit by hand -->".to_string(),
        String::new(),
        "# LIBCOB porting parity — typed C↔Rust symbol map".to_string(),
        String::new(),
        "> Produced by `gnucobol-rs-port-index` (PORT-INDEX.1): the admitted libcob C is parsed into a".to_string(),
        "> symbol index with **preprocessor status** (compiled / `#if 0` / config-gated), the Rust port is".to_string(),
        "> parsed into a **real-`fn`** index (comment/string-aware), and the two are joined. A C function".to_string(),
        "> counts as ported only when a real Rust `fn` of that name exists — a name appearing solely in a".to_string(),
        "> doc comment is a **doc-only false hit**, not a port. **Byte** parity is proven separately by the".to_string(),
        "> per-court oracle sweeps in `lab/verify-sealed-courts.sh`.".to_string(),
        String::new(),
        "Column meanings: **source** = function definitions in the `.c`; **compiled** = reached by the".to_string(),
        "preprocessor in the admitted build; **disabled** = `#if 0`/config-gated source mirrors;".to_string(),
        "**active/inactive/test** = real Rust `fn` counterpart kinds; **doc-only** = name only in a".to_string(),
        "comment (false hit, NOT a port); **missing** = absent; **active parity** = compiled fns with a".to_string(),
        "real Rust `fn` (active / inactive mirror / test). This is *symbol* parity, not behaviour parity —".to_string(),
        "oracle-backed *byte* parity is the separate per-court sweeps.".to_string(),
        String::new(),
        "| libcob file | source | compiled | disabled | active | inactive | test | doc-only | missing | active parity |".to_string(),
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|".to_string(),
    ];
    let (mut ts, mut tc, mut td, mut ta, mut ti, mut tt, mut tdo, mut tm, mut tok) =
        (0, 0, 0, 0, 0, 0, 0, 0, 0usize);
    for r in rows {
        l.push(format!(
            "| `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {:.1}% |",
            r.file, r.source_funcs, r.compiled, r.disabled, r.active_ported, r.inactive_mirrors,
            r.test_only, r.doc_only, r.missing, r.compiled_parity_pct
        ));
        ts += r.source_funcs;
        tc += r.compiled;
        td += r.disabled;
        ta += r.active_ported;
        ti += r.inactive_mirrors;
        tt += r.test_only;
        tdo += r.doc_only;
        tm += r.missing;
        tok += if r.compiled > 0 && r.gap.is_empty() { r.compiled } else { r.compiled - r.gap.len() };
    }
    let tpct = if tc > 0 { (tok as f64) * 1000.0 / (tc as f64) } else { 1000.0 };
    l.push(format!(
        "| **total** | **{ts}** | **{tc}** | **{td}** | **{ta}** | **{ti}** | **{tt}** | **{tdo}** | **{tm}** | **{:.1}%** |",
        tpct.round() / 10.0
    ));
    l.push(String::new());

    // Honest gap lists (compiled functions with no real Rust counterpart).
    let any_gap = rows.iter().any(|r| !r.gap.is_empty());
    l.push("## Gaps — compiled C functions with no real Rust `fn`".to_string());
    l.push(String::new());
    if any_gap {
        for r in rows {
            if !r.gap.is_empty() {
                l.push(format!("- **`{}`** ({}): `{}`", r.file, r.gap.len(), r.gap.join("`, `")));
            }
        }
    } else {
        l.push("None. Every compiled libcob function across all files has a real Rust counterpart.".to_string());
    }
    l.push(String::new());
    l.push("## How this is produced (reproducible)".to_string());
    l.push(String::new());
    l.push("`cargo run -p gnucobol-rs-port-index -- parity` joins two machine indexes under".to_string());
    l.push("`reports/port-index/` (`libcob-symbols.json`, `rust-symbols.json`, `parity-detailed.json`).".to_string());
    l.push("`-- check` is the anti-staleness gate (regenerate-and-diff). The C-side compiled set is".to_string());
    l.push("cross-checked by the doxygen parse (`DOXYGEN-PARITY.md`).".to_string());
    l.push(String::new());
    l.join("\n") + "\n"
}

/// The legacy-compatible `reports/libcob-parity.json` (consumed by the doxygen-compare gate): per file
/// `{file, functions, ported, parity_pct, missing}` where `missing` is the honest gap (no real `fn`).
pub fn legacy_json(rows: &[ParityRow]) -> Value {
    let mut files = Vec::new();
    let (mut tot, mut tot_p) = (0u64, 0u64);
    for r in rows {
        let ported = (r.active_ported + r.inactive_mirrors + r.test_only) as u64;
        let functions = r.source_funcs as u64;
        tot += functions;
        tot_p += ported;
        let pct = if functions > 0 { (ported as f64) * 1000.0 / (functions as f64) } else { 0.0 };
        files.push(json!({
            "file": r.file,
            "functions": functions,
            "ported": ported,
            "parity_pct": pct.round() / 10.0,
            "missing": r.gap,
        }));
    }
    let tpct = if tot > 0 { (tot_p as f64) * 1000.0 / (tot as f64) } else { 0.0 };
    json!({
        "schema": "libcob-porting-parity-v1",
        "court": "LIBCOB.PARITY.1",
        "generator": "gnucobol-rs-port-index (PORT-INDEX.1)",
        "oracle": "GnuCOBOL 3.2.0 (admitted; see reports/admission/RECEIPT-ADMISSION.md)",
        "method": "Typed symbol parity: a libcob function is PORTED only when a real Rust fn of that name exists in crates/gnucobol-rs/src (comment/string-aware; a doc-comment mention is a doc_only false hit, listed under missing). BYTE parity is proven separately by the per-court oracle sweeps.",
        "files": files,
        "totals": {"functions": tot, "ported": tot_p, "parity_pct": tpct.round() / 10.0},
    })
}

/// The rich detailed index (`reports/port-index/parity-detailed.json`).
pub fn detailed_json(rows: &[ParityRow]) -> Value {
    serde_json::to_value(rows).unwrap_or(Value::Null)
}

/// Render the PORT-INDEX.1 milestone receipt — stable methodology prose plus a **live** scoreboard
/// (regenerated from the join, so its numbers never go stale). Owned + freshness-gated by the port-index
/// tool: `generate` writes it, `check` fails on drift.
pub fn render_receipt(rows: &[ParityRow]) -> String {
    let done: Vec<&ParityRow> = rows.iter().filter(|r| r.compiled > 0 && r.gap.is_empty()).collect();
    let started: Vec<&ParityRow> =
        rows.iter().filter(|r| !r.gap.is_empty() && (r.active_ported + r.inactive_mirrors + r.test_only) > 0).collect();
    let tot_src: usize = rows.iter().map(|r| r.source_funcs).sum();
    let tot_compiled: usize = rows.iter().map(|r| r.compiled).sum();
    let tot_gap: usize = rows.iter().map(|r| r.gap.len()).sum();
    let tot_ok = tot_compiled - tot_gap;

    let mut l = vec![
        "<!-- generated by `cargo run -p gnucobol-rs-port-index -- parity` — do not edit by hand;".to_string(),
        "     freshness-gated by `gnucobol-rs-port-index check` (the scoreboard is regenerated from the".to_string(),
        "     live C↔Rust symbol join, so it can never go stale). -->".to_string(),
        String::new(),
        "# PORT-INDEX.1 — typed C↔Rust symbol parity (+ PORT-INDEX.1a false-closure repair)".to_string(),
        String::new(),
        "**Tool:** `crates/gnucobol-rs-port-index` · **Outputs:** `LIBCOB-PARITY.md`,".to_string(),
        "`reports/libcob-parity.json`, `reports/port-index/parity-detailed.json`.".to_string(),
        String::new(),
        "## What this seals".to_string(),
        String::new(),
        "PORT-INDEX.1 replaced grep / name-presence parity with **typed C↔Rust symbol parity**. It indexes".to_string(),
        format!("the {tot_src} admitted `libcob` source functions, classifies each by **preprocessor status**"),
        format!("({tot_compiled} compiled into the admitted oracle; the rest `#if 0` / config-gated), and joins them"),
        "against a **real-`fn`** index of the Rust port that is comment- and string-aware. A libcob function".to_string(),
        "counts as ported **only when a real Rust `fn` of that name exists** — a name appearing solely in a".to_string(),
        "doc comment is a `doc_only` false hit, never a port. PORT-INDEX.1a then closed every false hit it".to_string(),
        "exposed in the completed files (`numeric.c` 13, `move.c` 10, `cobgetopt.c` 1) by giving each faithful".to_string(),
        "Rust counterpart its **exact C name** (or adding the named wrapper).".to_string(),
        String::new(),
        format!("**Live total:** {tot_ok} / {tot_compiled} compiled libcob functions have a real Rust `fn` ({tot_gap} gap)."),
        String::new(),
        "## Completed files (100% active compiled-parity)".to_string(),
        String::new(),
        "| libcob file | source | compiled | active | inactive | doc-only | missing | active parity |".to_string(),
        "|---|---:|---:|---:|---:|---:|---:|---:|".to_string(),
    ];
    for r in &done {
        l.push(format!(
            "| `{}` | {} | {} | {} | {} | {} | {} | {:.1}% |",
            r.file, r.source_funcs, r.compiled, r.active_ported, r.inactive_mirrors, r.doc_only, r.missing,
            r.compiled_parity_pct
        ));
    }
    l.push(String::new());
    if !started.is_empty() {
        l.push("## In-progress files (partial — incremental subsystem ports)".to_string());
        l.push(String::new());
        l.push("| libcob file | source | compiled | active | gap | active parity |".to_string());
        l.push("|---|---:|---:|---:|---:|---:|".to_string());
        for r in &started {
            l.push(format!(
                "| `{}` | {} | {} | {} | {} | {:.1}% |",
                r.file, r.source_funcs, r.compiled, r.active_ported, r.gap.len(), r.compiled_parity_pct
            ));
        }
        l.push(String::new());
    }
    l.push("## Gates".to_string());
    l.push(String::new());
    l.push("`gnucobol-rs-port-index check` (anti-staleness: committed map == fresh re-derivation, and this".to_string());
    l.push("receipt's scoreboard == live) runs in both `lab/verify-sealed-courts.sh` and the docs-staleness".to_string());
    l.push("gate `lab/check-docs.sh`. It is complemented by the **C-vs-Rust doxygen** coverage gate".to_string());
    l.push("(`DOXYGEN-PARITY.md`, authoritative for the *compiled* C set — both the C and the native-Rust".to_string());
    l.push("doxygen are regenerated automatically so nothing needing a port slips through).".to_string());
    l.push(String::new());
    l.push("## Not claimed".to_string());
    l.push(String::new());
    l.push("Active parity is **symbol** parity — a real Rust `fn` exists — not behaviour parity (the oracle".to_string());
    l.push("sweeps) and not yet evidence-mapped. A future `function-evidence` milestone will add an".to_string());
    l.push("*evidenced* column linking each active function to its court / sweep / test receipt.".to_string());
    l.push(String::new());
    l.join("\n") + "\n"
}
