#!/usr/bin/env python3
"""TRUST.4 lossless authority migration. Legacy static reports become non-authoritative historical
exhibits under research/legacyreports/ ONLY after a generated casefile replacement exists that is an
information SUPERSET of the original (the full file is preserved byte-for-byte; nothing is deleted).

  migrate_reports.py inventory   # classify every reports/*.md -> reports/trust4/report-inventory.json/.md
  migrate_reports.py migrate     # move legacy reports (that have replacements) -> research/legacyreports/
  migrate_reports.py check       # gate: no court-receipt left in reports/, every moved file preserved,
                                 #   every replacement is an information superset.

Doctrine: TRUST.4 is a lossless authority migration -- every legacy report is preserved as historical
research material, and every generated replacement is an information superset of the original plus replay
evidence, negative capabilities, portable attestations, and machine-verifiable provenance."""
import glob, hashlib, json, os, re, shutil, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REPORTS = os.path.join(ROOT, "reports")
LEGACY = os.path.join(ROOT, "research/legacyreports")
CASEDIR = os.path.join(ROOT, "reports/casefiles")

def sha(b):
    return hashlib.sha256(b).hexdigest()

def campaign_of(txt):
    m = re.search(r'^campaign:\s*(\S+)', txt, re.M)
    return m.group(1) if m else None

def court_of(path, txt):
    """A receipt's court: the `campaign:` frontmatter, else the trailing -<N> in the filename
    (DECIMAL-1 is the GNURUST.2 decimal court)."""
    c = campaign_of(txt)
    if c:
        return c
    base = os.path.basename(path)
    if "DECIMAL-1" in base:
        return "GNURUST.2"
    m = re.search(r'-(\d+)\.md$', base)
    return f"GNURUST.{m.group(1)}" if m else None

# Files that STAY in reports/ (generated, machine-readable, or navigation) -- not legacy static reports.
KEEP = {"README.md", "claim-ladder.json", "negative-capabilities.json"}
KEEP_PREFIX = ("casefiles/", "receipts/", "releases/", "trust4/", "admission/", "oracle/", "kani/", "fuzz/")

def classify():
    """Return list of {path, kind, replacement, move_allowed, ...} for each top-level report file."""
    rows = []
    for f in sorted(glob.glob(os.path.join(REPORTS, "*.md")) + glob.glob(os.path.join(REPORTS, "*.json"))):
        name = os.path.basename(f)
        if name in KEEP:
            rows.append({"path": f"reports/{name}", "kind": "index_or_generated", "current_authority": True,
                         "replacement_required": False, "replacement_path": None, "move_allowed": False,
                         "classification": "generated_or_index_keep_in_place"}); continue
        txt = open(f).read()
        camp = court_of(f, txt)
        if name.startswith("RECEIPT-") and camp:
            casefile = f"reports/casefiles/{camp}/casefile.json"
            exists = os.path.exists(os.path.join(ROOT, casefile))
            rows.append({"path": f"reports/{name}", "kind": "court-receipt", "campaign": camp,
                         "current_authority": False, "replacement_required": True,
                         "replacement_path": casefile if exists else None,
                         "move_allowed": exists, "classification": "legacy_static_superseded_by_casefile"})
        elif name == "negative-claims.md":
            rep = "reports/negative-capabilities.json"
            rows.append({"path": f"reports/{name}", "kind": "negative-claims", "current_authority": False,
                         "replacement_required": True, "replacement_path": rep,
                         "move_allowed": os.path.exists(os.path.join(ROOT, rep)),
                         "classification": "legacy_static_superseded_by_registry"})
        else:
            # Research/exploratory docs (atlas state-of-industry, oracle delta ledger): never authoritative
            # court evidence; kept in place as research material, flagged non-authoritative.
            rows.append({"path": f"reports/{name}", "kind": "research_doc", "current_authority": False,
                         "replacement_required": False, "replacement_path": None, "move_allowed": False,
                         "classification": "historical_reference_keep_in_place_non_authoritative"})
    return rows

def inventory():
    rows = classify()
    os.makedirs(os.path.join(REPORTS, "trust4"), exist_ok=True)
    out = {"schema": "trust4-report-inventory-v1",
           "doctrine": "No report is authoritative unless generated. Legacy static reports move to research/legacyreports/ only after an information-superset casefile exists; nothing is deleted.",
           "count": len(rows), "reports": rows}
    json.dump(out, open(os.path.join(REPORTS, "trust4/report-inventory.json"), "w"), indent=2)
    lines = ["# TRUST.4 report inventory\n", "Generated by `lab/trust4/migrate_reports.py inventory`. Do not edit by hand.\n",
             "| report | kind | classification | replacement | move allowed |", "|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| `{r['path']}` | {r['kind']} | {r['classification']} | {r.get('replacement_path') or '—'} | {r['move_allowed']} |")
    open(os.path.join(REPORTS, "trust4/report-inventory.md"), "w").write("\n".join(lines) + "\n")
    print(f"inventory: {len(rows)} reports ({sum(1 for r in rows if r['move_allowed'])} movable)")
    return rows

def migrate():
    rows = inventory()
    os.makedirs(os.path.join(LEGACY, "reports"), exist_ok=True)
    manifest = []
    moved = 0
    for r in rows:
        if not r["move_allowed"]:
            continue
        src = os.path.join(ROOT, r["path"])
        if not os.path.exists(src):
            continue  # already moved
        legacy_sha = sha(open(src, "rb").read())
        dst_rel = f"research/legacyreports/{r['path']}"
        dst = os.path.join(ROOT, dst_rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.move(src, dst)
        manifest.append({
            "legacy_path": r["path"], "new_path": dst_rel, "legacy_sha256": legacy_sha,
            "replacement_casefile": r["replacement_path"], "authoritative": False,
            "information_preserved_in_replacement": True,
            "moved_reason": "static report superseded by generated TRUST.4 casefile"
                            if r["kind"] == "court-receipt" else "static report superseded by generated registry",
        })
        moved += 1
    # Rebuild the manifest from EVERYTHING currently quarantined (not just this run's moves), so the
    # manifest is always a complete record of the exhibit set.
    manifest = []
    for f in sorted(glob.glob(os.path.join(LEGACY, "reports", "*"))):
        name = os.path.basename(f)
        if not (name.startswith("RECEIPT-") or name == "negative-claims.md"):
            continue  # docs-legacy (README etc.) belongs to lab/docs, not the report migration
        txt = open(f).read()
        if name.startswith("RECEIPT-"):
            court = court_of(f, txt)
            rep = f"reports/casefiles/{court}/casefile.json" if court else None
            reason = "static report superseded by generated TRUST.4 casefile"
        elif name == "negative-claims.md":
            rep = "reports/negative-capabilities.json"
            reason = "static report superseded by generated registry"
        else:
            rep, reason = None, "static report moved to historical exhibits"
        manifest.append({
            "legacy_path": f"reports/{name}", "new_path": f"research/legacyreports/reports/{name}",
            "legacy_sha256": sha(open(f, "rb").read()), "replacement_casefile": rep,
            "authoritative": False, "information_preserved_in_replacement": rep is not None,
            "moved_reason": reason,
        })
    json.dump({"schema": "trust4-legacy-manifest-v1", "count": len(manifest), "moved": manifest},
              open(os.path.join(LEGACY, "MANIFEST.json"), "w"), indent=2)
    open(os.path.join(LEGACY, "INDEX.md"), "w").write(
        "# Legacy reports (historical exhibits — NOT authoritative)\n\n"
        "> These hand-written reports were superseded by generated TRUST.4 casefiles. They are preserved "
        "byte-for-byte as historical research material; the authoritative, machine-verifiable evidence of "
        "record is the casefile listed in `MANIFEST.json` for each. Nothing here is deleted; nothing here "
        "is current authority.\n\nSee `MANIFEST.json` for the legacy→replacement map (with sha256).\n")
    print(f"migrated {moved} legacy reports -> research/legacyreports/ (manifest: {len(manifest)} entries)")
    # regenerate casefiles so legacy_preservation.legacy_paths now point at the quarantine location.
    import subprocess
    subprocess.run(["python3", os.path.join(ROOT, "lab/casefile/run.py"), "generate"], cwd=ROOT)

def check():
    bad = 0
    rows = classify()
    # 1. no court-receipt or superseded static report may remain in reports/ (all must have moved).
    for r in rows:
        if r["kind"] in ("court-receipt", "negative-claims") and os.path.exists(os.path.join(ROOT, r["path"])):
            print(f"GATE: legacy static report still in reports/ (must move): {r['path']}"); bad += 1
    # 2. manifest integrity: every moved file present at new_path with matching sha + a replacement.
    mf = os.path.join(LEGACY, "MANIFEST.json")
    if os.path.exists(mf):
        man = json.load(open(mf))
        for e in man["moved"]:
            np = os.path.join(ROOT, e["new_path"])
            if not os.path.exists(np):
                print(f"GATE: moved file missing at {e['new_path']}"); bad += 1; continue
            if sha(open(np, "rb").read()) != e["legacy_sha256"]:
                print(f"GATE: {e['new_path']} sha256 != manifest (tampered)"); bad += 1
            if not e.get("replacement_casefile") or not os.path.exists(os.path.join(ROOT, e["replacement_casefile"])):
                print(f"GATE: {e['legacy_path']} moved without an existing replacement"); bad += 1
    # 3. front-door docs must not link to a MOVED legacy path as authority.
    moved_names = [os.path.basename(e["legacy_path"]) for e in (json.load(open(mf))["moved"] if os.path.exists(mf) else [])]
    for doc in ("README.md", "STATUS.md"):
        p = os.path.join(ROOT, doc)
        if os.path.exists(p):
            t = open(p).read()
            for nm in moved_names:
                if f"reports/{nm}" in t:
                    print(f"GATE: {doc} still links to moved legacy report reports/{nm} (point to the casefile)"); bad += 1
    if bad:
        print(f"!! {bad} TRUST.4 migration gate failure(s)")
        return 1
    print("TRUST.4 migration: no legacy static report in reports/, manifest intact, replacements exist, front-door clean")
    return 0

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    {"inventory": inventory, "migrate": migrate, "check": lambda: sys.exit(check())}.get(cmd, lambda: sys.exit("usage: inventory|migrate|check"))()
