#!/usr/bin/env python3
"""TRUST.4.DOCS -- generated documentation authority. Render authoritative docs from a structured model
(docs-src/<id>.model.json) + machine evidence (Cargo.toml, claim-ladder, casefiles, receipts), preserving
legacy content losslessly so the generated doc is an INFORMATION SUPERSET of the original.

  generate.py            # write all generated docs
  generate.py check      # FAIL if a generated doc != regenerated (manual edit / staleness), the version
                         #   drifts from Cargo.toml, legacy isn't preserved, or a court is unreflected.

Doctrine: TRUST.4.DOCS makes documentation a forensic artifact -- every authoritative document is generated
from structured evidence + preserved legacy content + negative capabilities + current replay state, and
staleness becomes a machine-detectable negative claim rather than a hidden documentation bug."""
import glob, hashlib, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "docs-src")

def sha(b):
    return hashlib.sha256(b if isinstance(b, bytes) else b.encode()).hexdigest()

def crate_version():
    for ln in open(os.path.join(ROOT, "crates/gnucobol-rs/Cargo.toml")):
        if ln.startswith("version"):
            return ln.split('"')[1]
    return "?"

def claim_ladder():
    return json.load(open(os.path.join(ROOT, "reports/claim-ladder.json")))

def oracle_str():
    for c in sorted(glob.glob(os.path.join(ROOT, "reports/receipts/*/receipt.json"))):
        o = json.load(open(c)).get("oracle", {})
        if o.get("version"):
            return o["version"]
    return "GnuCOBOL 3.2.0"

def machine_values():
    cl = claim_ladder()
    gnurust = [c for c in cl["courts"] if c["id"].startswith("GNURUST.")]
    casefiles = glob.glob(os.path.join(ROOT, "reports/casefiles/*/casefile.json"))
    def verdict(cid):
        jf = os.path.join(ROOT, "reports/casefiles", cid, "casefile.json")
        return json.load(open(jf))["results"]["verdict"] if os.path.exists(jf) else "?"
    rows = ["### Sealed courts (generated from `reports/claim-ladder.json`)", "",
            "| court | name | verdict | casefile |", "|---|---|---|---|"]
    for c in sorted(cl["courts"], key=lambda x: (x["id"].split(".")[0], int(re.sub(r'\D', '', x["id"].split(".")[-1]) or 0))):
        rows.append(f"| `{c['id']}` | {c.get('name','')} | {verdict(c['id'])} | `reports/casefiles/{c['id']}/` |")
    return {
        "version": crate_version(),
        "gnurust_court_count": str(len(gnurust)),
        "oracle": oracle_str(),
        "casefile_count": str(len(casefiles)),
        "publish_note": "(The git repo is the authority; crates.io may trail by a version under publish rate limits.)",
        "sealed_courts_table": "\n".join(rows),
    }

def header(model):
    lp = model["legacy_preservation"]
    return (f"<!--\nDO NOT EDIT BY HAND. Generated by lab/docs/generate.py from docs-src/{model['document_id']}.model.json\n"
            f"+ machine evidence (crates/gnucobol-rs/Cargo.toml, reports/claim-ladder.json, reports/casefiles/*,\n"
            f"reports/receipts/*). Regenerate: python3 lab/docs/generate.py. Check: python3 lab/docs/generate.py check.\n"
            f"Evidence authority: the claim-ladder + generated casefiles. Legacy source preserved (lossless) under\n"
            f"{lp['legacy_paths'][0]} (sha256 {lp['legacy_sha256'][0]}).\n-->\n\n"
            f"# {model['title']}\n\n"
            f"> _Generated document (TRUST.4.DOCS). Machine authority: `reports/claim-ladder.json` + "
            f"`reports/casefiles/`. Legacy source preserved losslessly under `{lp['legacy_paths'][0]}`._\n\n")

def render(model):
    body = model["body_template"]
    for k, v in machine_values().items():
        body = body.replace("{{" + k + "}}", v)
    return header(model) + body + "\n"

def models():
    return [json.load(open(f)) for f in sorted(glob.glob(os.path.join(SRC, "*.model.json")))]

def generate():
    for m in models():
        open(os.path.join(ROOT, m["generated_path"]), "w").write(render(m))
    print(f"generated {len(models())} authoritative doc(s) from docs-src/ models")

def check():
    bad = 0
    cv = crate_version()
    cl_ids = [c["id"] for c in claim_ladder()["courts"]]
    for m in models():
        gp = os.path.join(ROOT, m["generated_path"])
        if not os.path.exists(gp):
            print(f"NEG.DOC.LEGACY_NOT_REPLACED: {m['generated_path']} not generated"); bad += 1; continue
        actual = open(gp).read()
        expected = render(m)
        if actual != expected:
            print(f"NEG.DOC.MANUAL_EDIT: {m['generated_path']} != regenerated (hand-edited or stale; run lab/docs/generate.py)"); bad += 1
        # version freshness
        if f"gnucobol-rs {cv}" not in actual:
            print(f"NEG.DOC.STALE_VERSION: {m['generated_path']} does not name current version {cv}"); bad += 1
        # legacy preserved as a superset
        lp = m.get("legacy_preservation")
        if not lp:
            print(f"NEG.DOC.INFORMATION_LOSS: {m['generated_path']} model lacks legacy_preservation"); bad += 1
        else:
            lpath = os.path.join(ROOT, lp["legacy_paths"][0])
            if not os.path.exists(lpath):
                print(f"NEG.DOC.LEGACY_NOT_REPLACED: legacy source missing {lp['legacy_paths'][0]}"); bad += 1
            elif sha(open(lpath, "rb").read()) not in lp["legacy_sha256"]:
                print(f"NEG.DOC.INFORMATION_LOSS: {m['generated_path']} legacy_sha256 != actual legacy file"); bad += 1
            if not lp.get("information_superset") or lp.get("missing_items"):
                print(f"NEG.DOC.INFORMATION_LOSS: {m['generated_path']} not an information superset"); bad += 1
        # sealed courts reflected (STATUS embeds the generated table, so every court id appears)
        if m["document_id"] == "STATUS":
            for cid in cl_ids:
                if cid not in actual:
                    print(f"NEG.DOC.STALE_CLAIM: STATUS missing claim-ladder court {cid}"); bad += 1
    if bad:
        print(f"!! {bad} TRUST.4.DOCS finding(s) -- regenerate: python3 lab/docs/generate.py")
        return 1
    print(f"TRUST.4.DOCS: all {len(models())} generated doc(s) current, version fresh, legacy preserved as superset")
    return 0

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "generate"
    if cmd == "generate":
        generate()
    elif cmd == "check":
        sys.exit(check())
    else:
        print("usage: generate.py generate|check"); sys.exit(2)
