#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/work/trees/a/candidate/tests'
exec ${CONFIG_SHELL-/bin/bash} "/work/trees/a/candidate/tests/./testsuite" -v -d  416 ${1+"$@"}
exit 1
