//! Generates `COBOL-PARITY.md` -- the full-language 1:1 parity tracker. It enumerates EVERY aspect of
//! what GnuCOBOL does (the 66 statement verbs from `cobc/parser.y`, the 110 intrinsic functions from
//! `libcob/intrinsic.c`, the data-description clauses, the USAGE forms, and the 13 libcob runtime
//! files -- the authoritative surface in `data/gnucobol_surface.json`) and, for each, reports our
//! port status on two axes:
//!
//!   * **Runtime** -- is the libcob primitive ported 1:1? (from the doxygen C-vs-Rust parity:
//!     `reports/doxygen-parity.json`; every admitted libcob file is 100%, so every statement's runtime
//!     semantics + every intrinsic is ported.)
//!   * **Front-end** -- can the native interpreter (`src/frontend.rs`) actually RUN it? (from the live
//!     `WIRED_STATEMENTS` marker the front-end exports.)
//!
//! The gap between the two axes IS the "what is missing" list: the runtime is the engine (done); the
//! front-end is the steering (in progress). `check` regenerates + diffs (anti-staleness), wired into
//! the doc-refresh gate.
use serde_json::Value;
use std::path::Path;

const SURFACE: &str = include_str!("data/gnucobol_surface.json");
const FILES: &str = include_str!("data/gnucobol_files.json");

const FILE_HEADER: &str = "\
<!-- generated by `cargo run -p xtask -- cobol-parity generate` -- do not edit by hand -->

# GnuCOBOL 3.2 -> gnucobol-rs FILE CENSUS -- every file accounted for, with a gap note + plan

> Goal: **not a single file** of the admitted GnuCOBOL 3.2 source is left unaccounted for. Every file
> is enumerated below with its parity status and -- where it is not already done -- a concrete plan to
> bring it to full parity. Statuses: **PORTED**/**PORTED+EVIDENCED** (1:1 in the runtime, oracle-sealed)
> · **COPIED+WIRED** (config copied verbatim + parsed natively) · **PARTIAL** (e.g. runtime messages) ·
> **GAP -> front-end / cobrun** (the clean-room interpreter roadmap) · **OBVIATED** (build system that
> Cargo replaces) · **CONSUMED-AS-ORACLE** (the GnuCOBOL test suite, used as the oracle) ·
> **REFERENCE** / **TEST-DATA**.
";

/// Build `FILE-PARITY.md` -- the per-file census of the whole GnuCOBOL 3.2 tree.
fn build_files() -> String {
    let m: Value = serde_json::from_str(FILES).unwrap_or(Value::Null);
    let files = m["files"].as_array().cloned().unwrap_or_default();
    let mut out = String::from(FILE_HEADER);

    // summary by status.
    let mut counts: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    for f in &files {
        *counts.entry(f["status"].as_str().unwrap_or("?").to_string()).or_default() += 1;
    }
    out.push_str(&format!("## Summary -- {} files total\n\n| status | files | meaning |\n|---|---:|---|\n", files.len()));
    let meaning = |s: &str| match s {
        "PORTED+EVIDENCED" => "1:1 in the runtime, oracle-sealed",
        "PORTED" => "ported (API header / support unit)",
        "PORTED-VIA" => "folded into a ported module",
        "COPIED+WIRED" => "config copied verbatim + parsed natively",
        "PARTIAL" => "partially reproduced (e.g. runtime messages)",
        "GAP -> front-end" => "**active gap** -- reimplement in the clean-room front-end",
        "GAP -> cobrun" => "**active gap** -- grow the cobrun CLI",
        "OBVIATED" => "build system -- Cargo/xtask replaces it (no port needed)",
        "CONSUMED-AS-ORACLE" => "GnuCOBOL test corpus, used AS the oracle",
        "REFERENCE" => "documentation / license -- reference, not ported",
        "TEST-DATA" => "sample copybooks -- front-end test data",
        _ => "triage",
    };
    for (s, n) in &counts {
        out.push_str(&format!("| **{s}** | {n} | {} |\n", meaning(s)));
    }
    let active: usize = files.iter().filter(|f| f["status"].as_str().unwrap_or("").starts_with("GAP") || f["status"] == "PARTIAL").count();
    let evidenced: usize = files.iter().filter(|f| !f["evidence"].as_str().unwrap_or("").starts_with("UNEVIDENCED")).count();
    let unevidenced: usize = files.len() - evidenced;
    out.push_str(&format!(
        "\n**Receipts: every one of the {tot} files carries a receipt** -- {ev} with positive evidence \
         (the Rust module / config copy / test / oracle role that proves it is accounted for) and {un} \
         explicitly marked **UNEVIDENCED-GAP** with a plan (nothing is silently omitted). \
         **Active gaps: {active} files** (the cobc compiler -> clean-room front-end, the CLI drivers -> \
         `cobrun`, and the partial runtime-message reproduction). Everything else is ported, copied, \
         obviated by Cargo, or reference. The plans are the road to full 1:1 parity.\n\n",
        tot = files.len(), ev = evidenced, un = unevidenced,
    ));

    // the active-gap list first (the actionable part).
    out.push_str("## Active gaps (the road to full parity)\n\n| file | category | plan |\n|---|---|---|\n");
    for f in &files {
        let st = f["status"].as_str().unwrap_or("");
        if st.starts_with("GAP") || st == "PARTIAL" {
            out.push_str(&format!("| `{}` | {} | {} |\n", f["path"].as_str().unwrap_or(""), f["category"].as_str().unwrap_or(""), f["plan"].as_str().unwrap_or("")));
        }
    }

    // every file, grouped by top-level directory.
    out.push_str("\n## Every file (grouped by directory)\n\n");
    let mut by_dir: std::collections::BTreeMap<String, Vec<&Value>> = std::collections::BTreeMap::new();
    for f in &files {
        let path = f["path"].as_str().unwrap_or("");
        let dir = path.split('/').next().filter(|_| path.contains('/')).unwrap_or("(top level)").to_string();
        by_dir.entry(dir).or_default().push(f);
    }
    for (dir, items) in &by_dir {
        out.push_str(&format!("### `{}/` ({} files)\n\n| file | status | receipt / evidence |\n|---|---|---|\n", dir, items.len()));
        for f in items {
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                f["path"].as_str().unwrap_or(""),
                f["status"].as_str().unwrap_or(""),
                f["evidence"].as_str().unwrap_or(f["gap"].as_str().unwrap_or("")),
            ));
        }
        out.push('\n');
    }
    out.push_str(
        "_Generated from a committed snapshot of the admitted GnuCOBOL 3.2 file tree \
         (`xtask/src/data/gnucobol_files.json`), classified by path rule. Regenerate with \
         `cargo run -p xtask -- cobol-parity generate`; the doc-refresh gate fails on drift._\n",
    );
    out
}

const HEADER: &str = "\
<!-- generated by `cargo run -p xtask -- cobol-parity generate` -- do not edit by hand -->

# COBOL 1:1 parity tracker -- everything GnuCOBOL does, and our native-Rust status

> The goal: the Rust port natively does **everything** GnuCOBOL does. This tracks every aspect of the
> language + runtime against two axes -- **Runtime** (is the `libcob` primitive ported 1:1?) and
> **Front-end** (can the native interpreter `cobrun` actually run it?). The authoritative surface is
> derived from the admitted GnuCOBOL 3.2 source (`cobc/parser.y` statements, `libcob/intrinsic.c`
> functions, `cobc/reserved.c` clauses). The gap between the two axes is exactly what is left to build.
";

fn read_json(p: &Path) -> Value {
    std::fs::read_to_string(p).ok().and_then(|s| serde_json::from_str(&s).ok()).unwrap_or(Value::Null)
}

/// The set of libcob files that are 100% ported (from the doxygen C-vs-Rust parity view). Used to mark
/// a statement's runtime semantics as ported when its implementing file is complete.
fn ported_files(root: &str) -> Vec<String> {
    let dox = read_json(&Path::new(root).join("reports/doxygen-parity.json"));
    let mut v = Vec::new();
    // doxygen-parity.json is an array of {file, fns, ported, ...} or a {files:[...]} -- handle both.
    let files = dox.get("files").and_then(|f| f.as_array()).cloned().or_else(|| dox.as_array().cloned()).unwrap_or_default();
    for f in &files {
        let name = f.get("file").and_then(|n| n.as_str()).unwrap_or("");
        let total = f.get("doxygen_functions").and_then(|n| n.as_i64()).unwrap_or(0);
        let done = f.get("ported").and_then(|n| n.as_i64()).unwrap_or(0);
        let pct = f.get("parity_pct").and_then(|n| n.as_f64()).unwrap_or(0.0);
        if !name.is_empty() && (pct >= 100.0 || (total > 0 && done == total)) {
            v.push(name.to_string());
        }
    }
    v
}

/// The front-end's wired statement verbs, parsed live from `src/frontend.rs`'s `WIRED_STATEMENTS`.
fn wired_verbs(root: &str) -> Vec<String> {
    let src = std::fs::read_to_string(Path::new(root).join("crates/gnucobol-rs/src/frontend.rs")).unwrap_or_default();
    let mut out = Vec::new();
    if let Some(start) = src.find("pub const WIRED_STATEMENTS") {
        // skip past the type `&[&str] =` to the array literal `&[ ... ]` after the '='.
        let after_eq = src[start..].find('=').map(|e| start + e).unwrap_or(start);
        if let Some(open) = src[after_eq..].find('[') {
            let from = after_eq + open + 1;
            if let Some(close) = src[from..].find(']') {
                let body = &src[from..from + close];
                for tok in body.split(',') {
                    let t = tok.trim().trim_matches('"').trim();
                    if !t.is_empty() {
                        out.push(t.to_string());
                    }
                }
            }
        }
    }
    out
}

/// Does our crate define an intrinsic (`cob_intr_<name>` or a clearly-named port) in src?
fn intr_ported(root: &str, name: &str) -> bool {
    // every libcob/intrinsic.c function is ported (file is 100%); confirm the symbol is present.
    let needle = format!("cob_intr_{name}");
    let src_dir = Path::new(root).join("crates/gnucobol-rs/src");
    walk_contains(&src_dir, &needle)
}

fn walk_contains(dir: &Path, needle: &str) -> bool {
    if let Ok(rd) = std::fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_file() && p.extension().map(|x| x == "rs").unwrap_or(false) {
                if let Ok(s) = std::fs::read_to_string(&p) {
                    if s.contains(needle) {
                        return true;
                    }
                }
            }
        }
    }
    false
}

fn build(root: &str) -> String {
    let surface: Value = serde_json::from_str(SURFACE).unwrap_or(Value::Null);
    let ported = ported_files(root);
    let is_ported = |m: &str| -> bool {
        if m == "-" {
            return false; // compiler-generated control flow: no libcob primitive
        }
        m.split('/').any(|part| {
            let f = part.trim();
            ported.iter().any(|pf| pf == f)
        })
    };
    let wired = wired_verbs(root);
    let mut out = String::from(HEADER);

    // ---- summary first (computed below, but written after the tables via a placeholder pass) ----
    let statements = surface["statements"].as_array().cloned().unwrap_or_default();
    let intr = surface["intrinsic_functions"].as_array().cloned().unwrap_or_default();
    let clauses = surface["data_clauses"].as_array().cloned().unwrap_or_default();
    let usages = surface["usages"].as_array().cloned().unwrap_or_default();
    let libcob = surface["libcob_files"].as_array().cloned().unwrap_or_default();

    // counts.
    let mut st_runtime = 0usize;
    let mut st_wired = 0usize;
    for s in &statements {
        let m = s["runtime_module"].as_str().unwrap_or("-");
        let verb = s["verb"].as_str().unwrap_or("");
        if is_ported(m) {
            st_runtime += 1;
        }
        if wired.iter().any(|w| w == verb) {
            st_wired += 1;
        }
    }
    let intr_done = intr.iter().filter(|n| intr_ported(root, n.as_str().unwrap_or(""))).count();
    let libcob_done = libcob.iter().filter(|f| ported.iter().any(|pf| pf == f.as_str().unwrap_or(""))).count();

    out.push_str("## Summary\n\n");
    out.push_str(&format!(
        "| surface | total | runtime ported (1:1) | front-end runs it |\n|---|---:|---:|---:|\n\
         | libcob runtime files | {lt} | **{ld} ({lp:.0}%)** | n/a |\n\
         | statements (verbs) | {st} | {sr} ({srp:.0}%) | **{sw} ({swp:.0}%)** |\n\
         | intrinsic functions | {it} | **{idn} ({ip:.0}%)** | 0 (0%) |\n\
         | data-description clauses | {ct} | (runtime via move/layout) | see table |\n\
         | USAGE forms | {ut} | (runtime ported) | see table |\n\n",
        lt = libcob.len(), ld = libcob_done, lp = pct(libcob_done, libcob.len()),
        st = statements.len(), sr = st_runtime, srp = pct(st_runtime, statements.len()),
        sw = st_wired, swp = pct(st_wired, statements.len()),
        it = intr.len(), idn = intr_done, ip = pct(intr_done, intr.len()),
        ct = clauses.len(), ut = usages.len(),
    ));
    out.push_str(
        "**Reading this:** the **runtime engine is ~100%** -- every admitted libcob file and every \
         intrinsic is ported 1:1 and oracle-sealed. The **front-end** (the native interpreter that \
         turns source into runtime calls) is the remaining work; the statements/clauses it does not \
         yet run are the 1:1-parity TODO list below.\n\n",
    );

    // ---- statements table ----
    out.push_str("## Statements (the verb surface, from `cobc/parser.y`)\n\n");
    out.push_str("| statement | category | runtime (libcob) | front-end (cobrun) | status |\n");
    out.push_str("|---|---|:---:|:---:|---|\n");
    let mut by_cat: std::collections::BTreeMap<String, Vec<&Value>> = std::collections::BTreeMap::new();
    for s in &statements {
        by_cat.entry(s["category"].as_str().unwrap_or("other").to_string()).or_default().push(s);
    }
    for (_, items) in &by_cat {
        for s in items {
            let name = s["name"].as_str().unwrap_or("");
            let cat = s["category"].as_str().unwrap_or("");
            let m = s["runtime_module"].as_str().unwrap_or("-");
            let verb = s["verb"].as_str().unwrap_or("");
            let rt = if m == "-" { "n/a".to_string() } else if is_ported(m) { format!("yes ({m})") } else { format!("no ({m})") };
            let fe = wired.iter().any(|w| w == verb);
            let status = if fe {
                "**DONE** -- parses + runs"
            } else if m == "-" {
                "front-end TODO (compiler control flow)"
            } else if is_ported(m) {
                "RUNTIME-ONLY -- libcob ported, front-end not wired"
            } else {
                "missing"
            };
            out.push_str(&format!("| `{name}` | {cat} | {rt} | {} | {status} |\n", if fe { "**yes**" } else { "no" }));
        }
    }

    // ---- intrinsic functions ----
    out.push_str("\n## Intrinsic functions (`FUNCTION ...`, from `libcob/intrinsic.c`)\n\n");
    out.push_str(&format!(
        "All **{}** intrinsic functions are ported 1:1 in the runtime ({}/{} confirmed present as \
         `cob_intr_*` in the port; `intrinsic.c` is 100% in the doxygen parity). The front-end does not \
         yet evaluate `FUNCTION ...` references in expressions (0 wired) -- wiring them is cheap since \
         the runtime is done. The full list:\n\n",
        intr.len(), intr_done, intr.len(),
    ));
    let names: Vec<String> = intr.iter().map(|n| n.as_str().unwrap_or("").to_uppercase().replace('_', "-")).collect();
    out.push_str("> ");
    out.push_str(&names.join(", "));
    out.push_str("\n\n");

    // ---- data clauses + usages ----
    out.push_str("## Data-description clauses\n\n| clause | front-end (cobrun) |\n|---|:---:|\n");
    let fe_clause = |c: &str| matches!(c, "PICTURE" | "VALUE" | "FILLER");
    for c in &clauses {
        let name = c.as_str().unwrap_or("");
        out.push_str(&format!("| `{name}` | {} |\n", if fe_clause(name) { "**yes**" } else { "no (runtime ready)" }));
    }
    out.push_str("\n## USAGE forms\n\n| usage | front-end (cobrun) |\n|---|:---:|\n");
    let fe_usage = |u: &str| u == "DISPLAY";
    for u in &usages {
        let name = u.as_str().unwrap_or("");
        out.push_str(&format!("| `{name}` | {} |\n", if fe_usage(name) { "**yes**" } else { "no (runtime ready)" }));
    }

    // ---- provenance ----
    out.push_str("\n## Provenance + method\n\n");
    out.push_str(&format!("{}\n\n", surface["provenance"].as_str().unwrap_or("")));
    out.push_str(
        "Regenerate with `cargo run -p xtask -- cobol-parity generate`. The status columns are computed \
         live: runtime from `reports/doxygen-parity.json`, front-end from the `WIRED_STATEMENTS` marker \
         in `src/frontend.rs`. As statements are wired into the front-end, regenerating updates this \
         doc; the doc-refresh gate (`lab/check-docs.sh`) fails if it drifts.\n",
    );
    out
}

fn pct(done: usize, total: usize) -> f64 {
    if total == 0 {
        0.0
    } else {
        100.0 * done as f64 / total as f64
    }
}

pub fn run(cmd: &str, root: &str) -> i32 {
    let docs = [
        (Path::new(root).join("COBOL-PARITY.md"), build(root)),
        (Path::new(root).join("FILE-PARITY.md"), build_files()),
    ];
    match cmd {
        "generate" => {
            for (path, text) in &docs {
                if std::fs::write(path, text).is_err() {
                    eprintln!("cobol-parity: failed to write {}", path.display());
                    return 2;
                }
            }
            println!("COBOL-PARITY.md + FILE-PARITY.md generated");
            0
        }
        "check" => {
            for (path, text) in &docs {
                let committed = std::fs::read_to_string(path).unwrap_or_default();
                if &committed != text {
                    eprintln!("{} STALE: != `xtask cobol-parity generate`. Re-run it.", path.display());
                    return 2;
                }
            }
            println!("COBOL-PARITY + FILE-PARITY: fresh (regeneration-equal)");
            0
        }
        _ => {
            eprintln!("usage: xtask cobol-parity <generate|check>");
            2
        }
    }
}
