//! GNURUST.COVERAGE.1 — forensic coverage map. Port of lab/coverage/run.py. The surface table is the source
//! of truth (embedded from data); the logic re-derives module presence + counts + validates the mappings.
use serde_json::{json, Value};
use std::path::Path;

const SURFACES_JSON: &str = include_str!("coverage_surfaces.json");
const HEADER_JSON: &str = include_str!("coverage_header.json");
const STATUSES: [&str; 4] = ["sealed", "observed", "negative", "missing"];
const EXCLUDED: [&str; 23] = [
    "GNURUST.COVERAGE.1",
    "GNURUST.PUBLIC.CORPUS.1",
    "GNURUST.BUILD.PROFILE.1",
    "GNURUST.PUBLIC.GAP.1",
    "GNURUST.GNUCOBOL-TESTSUITE.1",
    "GNURUST.GNUCOBOL-TESTSUITE.2",
    "GNURUST.GNUCOBOL-TESTSUITE.3",
    "GNURUST.GNUCOBOL-RUNTIME-MATH.1",
    "GNURUST.METHODOLOGY.LIBCOB.1",
    "GNURUST.METHODOLOGY.PARSER.1",
    "GNURUST.COBC-RS.ARGS.1",
    "GNURUST.COBC-RS.LAUNCHER.1",
    "GNURUST.COBC-RS.PARALLEL.1",
    "GNURUST.COBC-RS.NATIVE-MODE-BOUNDARY.1",
    "GNURUST.COBC-RS.POLICY-COMPLETE.1",
    "GNURUST.MODULE.REGISTRY.1",
    "GNURUST.MODULE.CALL.1",
    "GNURUST.MODULE.CANCEL.1",
    "GNURUST.MODULE.SEARCH.1",
    "GNURUST.MODULE.PARALLEL.1",
    "GNURUST.GNUCOBOL-TESTSUITE.4",
    "GNURUST.GNUCOBOL-TESTSUITE.BOUNDARY-REDUCTION.1",
    "GNURUST.GNUCOBOL-RUNTIME-MATH.2",
];

fn read_json(p: &Path) -> Value {
    std::fs::read_to_string(p)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(Value::Null)
}

fn claim_ids(root: &str) -> Vec<String> {
    read_json(&Path::new(root).join("reports/claim-ladder.json"))["courts"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|c| c["id"].as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default()
}

fn build(root: &str) -> Value {
    let src = Path::new(root).join("lab/admit/gnucobol-3.2");
    let table: Vec<Value> = serde_json::from_str(SURFACES_JSON).unwrap_or_default();
    let header: Value = serde_json::from_str(HEADER_JSON).unwrap_or_default();
    let mut rows = Vec::new();
    for s in &table {
        let mods: Vec<&str> = s["source_modules"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|m| m.as_str())
            .collect();
        let present = mods.iter().all(|m| src.join(m).exists());
        rows.push(json!({
            "surface": s["surface"], "category": s["category"], "source_modules": s["source_modules"],
            "source_modules_present": present, "status": s["status"], "courts": s["courts"],
            "future_campaign": s["future_campaign"], "risk_if_unported": s["risk_if_unported"]
        }));
    }
    let count = |st: &str| rows.iter().filter(|r| r["status"] == st).count();
    let total = rows.len();
    let counts = json!({"sealed": count("sealed"), "observed": count("observed"), "negative": count("negative"), "missing": count("missing")});
    json!({
        "schema": "gnurust-coverage-v1", "court": "GNURUST.COVERAGE.1",
        "doctrine": header["doctrine"], "oracle_source": header["oracle_source"],
        "surface_count": total, "status_counts": counts,
        "sealed_fraction": format!("{}/{}", count("sealed"), total),
        "honest_note": header["honest_note"], "surfaces": rows,
        "non_claims": ["NEG.COVERAGE.NOT_A_COMPLETENESS_CLAIM","NEG.COVERAGE.SURFACE_LIST_NOT_EXHAUSTIVE","NEG.COVERAGE.STATUS_NOT_QUALITY","NEG.COVERAGE.NO_NEW_TRUTH"]
    })
}

fn basename(m: &str) -> &str {
    m.rsplit('/').next().unwrap_or(m)
}

fn render_md(c: &Value) -> String {
    let sc = &c["status_counts"];
    let badge = |s: &str| match s {
        "sealed" => "✅",
        "observed" => "🟡",
        "negative" => "⛔",
        _ => "❌",
    };
    let mut l = vec![
        "<!-- generated by xtask coverage — do not edit by hand -->".to_string(), String::new(),
        "# GNURUST.COVERAGE.1 — forensic coverage map of GnuCOBOL".to_string(), String::new(),
        "> [!IMPORTANT]".to_string(), format!("> {}", c["honest_note"].as_str().unwrap_or("")), String::new(),
        format!("- surfaces: **{}**  ·  sealed ✅ **{}**  ·  observed 🟡 {}  ·  refused ⛔ {}  ·  **missing ❌ {}**", c["surface_count"], sc["sealed"], sc["observed"], sc["negative"], sc["missing"]),
        String::new(),
        format!("- sealed fraction (data-representation spine): **{}**", c["sealed_fraction"].as_str().unwrap_or("")),
        String::new(),
        "| surface | category | source | status | courts / future |".to_string(), "|---|---|---|:---:|---|".to_string(),
    ];
    for r in c["surfaces"].as_array().unwrap() {
        let courts = r["courts"].as_array().unwrap();
        let cf = if !courts.is_empty() {
            courts
                .iter()
                .filter_map(|x| x.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        } else {
            r["future_campaign"].as_str().unwrap_or("—").to_string()
        };
        let mods = r["source_modules"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|m| m.as_str())
            .map(basename)
            .collect::<Vec<_>>()
            .join(", ");
        l.push(format!(
            "| `{}` | {} | `{}` | {} {} | {} |",
            r["surface"].as_str().unwrap(),
            r["category"].as_str().unwrap(),
            mods,
            badge(r["status"].as_str().unwrap()),
            r["status"].as_str().unwrap(),
            cf
        ));
    }
    l.extend([
        "".to_string(),
        "## Risk of the unported surfaces (missing ❌)".to_string(),
        String::new(),
    ]);
    for r in c["surfaces"].as_array().unwrap() {
        if r["status"] == "missing" {
            l.push(format!(
                "- **`{}`** → `{}`: {}",
                r["surface"].as_str().unwrap(),
                r["future_campaign"].as_str().unwrap_or(""),
                r["risk_if_unported"].as_str().unwrap_or("")
            ));
        }
    }
    l.extend(["".to_string(), "## Non-claims".to_string(), String::new()]);
    for n in c["non_claims"].as_array().unwrap() {
        l.push(format!("- `{}`", n.as_str().unwrap()));
    }
    l.push(String::new());
    l.join("\n") + "\n"
}

// structural-equality canonicalization (mirror Python json.dumps sort_keys comparison)
fn canon(v: &Value) -> String {
    serde_json::to_string(&sorted(v)).unwrap_or_default()
}
fn sorted(v: &Value) -> Value {
    match v {
        Value::Object(m) => {
            let mut bt: std::collections::BTreeMap<String, Value> =
                std::collections::BTreeMap::new();
            for (k, val) in m {
                bt.insert(k.clone(), sorted(val));
            }
            json!(bt)
        }
        Value::Array(a) => Value::Array(a.iter().map(sorted).collect()),
        _ => v.clone(),
    }
}

pub fn run(cmd: &str, root: &str) -> i32 {
    let fresh = build(root);
    match cmd {
        "generate" => {
            let _ = std::fs::write(
                Path::new(root).join("reports/gnurust-coverage.json"),
                serde_json::to_vec_pretty(&fresh).unwrap_or_default(),
            );
            let _ = std::fs::write(
                Path::new(root).join("reports/gnurust-coverage.md"),
                render_md(&fresh),
            );
            let sc = &fresh["status_counts"];
            println!(
                "coverage: {} surfaces — sealed {}, observed {}, refused {}, MISSING {}",
                fresh["surface_count"], sc["sealed"], sc["observed"], sc["negative"], sc["missing"]
            );
            0
        }
        "check" => {
            let mut bad = 0;
            let jp = Path::new(root).join("reports/gnurust-coverage.json");
            if !jp.exists() {
                println!("GATE: reports/gnurust-coverage.json missing");
                return 1;
            }
            if canon(&read_json(&jp)) != canon(&fresh) {
                println!("GATE: coverage map != a fresh re-derive (stale or hand-edited)");
                bad += 1;
            }
            if std::fs::read_to_string(Path::new(root).join("reports/gnurust-coverage.md"))
                .unwrap_or_default()
                != render_md(&fresh)
            {
                println!("GATE: coverage .md != regenerated");
                bad += 1;
            }
            let cl = claim_ids(root);
            let mapped: std::collections::HashSet<String> = fresh["surfaces"]
                .as_array()
                .unwrap()
                .iter()
                .flat_map(|r| {
                    r["courts"]
                        .as_array()
                        .unwrap()
                        .iter()
                        .filter_map(|c| c.as_str().map(String::from))
                })
                .collect();
            let mut admitted: Vec<String> = cl
                .iter()
                .filter(|c| {
                    (c.starts_with("GNURUST.") || c.contains("ATLAS"))
                        && !EXCLUDED.contains(&c.as_str())
                })
                .cloned()
                .collect();
            admitted.sort();
            for court in &admitted {
                if !mapped.contains(court) {
                    println!("GATE: admitted court {court} is NOT mapped to any coverage surface");
                    bad += 1;
                }
            }
            for r in fresh["surfaces"].as_array().unwrap() {
                for court in r["courts"].as_array().unwrap() {
                    let court = court.as_str().unwrap();
                    if !cl.iter().any(|c| c == court) {
                        println!(
                            "GATE: surface {} declares court {court} not in the claim-ladder",
                            r["surface"].as_str().unwrap()
                        );
                        bad += 1;
                    }
                }
                if r["status"] == "sealed" && r["courts"].as_array().unwrap().is_empty() {
                    println!(
                        "GATE: surface {} is 'sealed' but has no court",
                        r["surface"].as_str().unwrap()
                    );
                    bad += 1;
                }
                if !STATUSES.contains(&r["status"].as_str().unwrap()) {
                    println!(
                        "GATE: surface {} has invalid status",
                        r["surface"].as_str().unwrap()
                    );
                    bad += 1;
                }
                if !r["source_modules_present"].as_bool().unwrap_or(false) {
                    println!(
                        "GATE: surface {} binds to a missing source module",
                        r["surface"].as_str().unwrap()
                    );
                    bad += 1;
                }
            }
            if bad > 0 {
                println!("!! {bad} GNURUST.COVERAGE.1 finding(s)");
                return 1;
            }
            let sc = &fresh["status_counts"];
            println!("GNURUST.COVERAGE.1: {} surfaces mapped to admitted source; every admitted court mapped; sealed {}, MISSING {}; fresh", fresh["surface_count"], sc["sealed"], sc["missing"]);
            0
        }
        _ => {
            eprintln!("usage: coverage generate|check");
            2
        }
    }
}
