//! Generates `GAP-ANALYSIS.md` -- the forensic C->Rust porting gap ledger. The brief: note EVERY gap
//! between the admitted GnuCOBOL 3.2 C and the gnucobol-rs Rust port, each as a *diff* (what the C does,
//! what the port does, the precise divergence), so the porting record is timelessly complete -- including
//! gaps an expert would miss.
//!
//! The findings come from a five-panel elite forensic audit (memory/ABI/UB; numeric/float/decimal;
//! OS/files/linking/concurrency; locale/encoding/i18n; build/dialect/exception/CLI). Each panel read both
//! codebases for code-cited divergences; the consolidated, committed snapshot lives in
//! `data/porting_gaps.json`. This doc is generated from it and freshness-gated (the doc-refresh gate fails
//! on drift), so the gap ledger can never silently rot.
//!
//! Severity legend: **high** = an oracle-observable divergence on a real program; **medium** = observable
//! under a stated trigger (a dialect, a non-C locale, an error path); **low** = narrow / faithful-but-
//! surprising; **latent** = no oracle-observable divergence today (admitted UB, capacity bound, or a
//! faithful value-port of an OS boundary). A gap is not a defect: the port models observable byte behavior
//! on the pinned x86-64 / C.UTF-8 / default-dialect oracle and declares every OS-mutating leaf a boundary.
use serde_json::Value;
use std::path::Path;

const GAPS: &str = include_str!("data/porting_gaps.json");

const HEADER: &str = "\
<!-- generated by `cargo run -p xtask -- gap-analysis generate` -- do not edit by hand -->

# GnuCOBOL 3.2 -> gnucobol-rs FORENSIC GAP ANALYSIS -- every divergence, as a diff

> **Brief.** Note **every single gap** between the original GnuCOBOL 3.2 (C) and gnucobol-rs (native
> Rust), no matter how small, each recorded as a *diff*: what the C does, what the port does, the precise
> divergence, whether it is observable in byte output, its severity, and the evidence/plan to close or
> admit it. The intent is information completeness -- a porting record that stays useful for as long as
> the port exists, including the non-obvious gaps an expert would miss.
>
> **Method.** Five specialist panels each read *both* codebases -- the admitted GnuCOBOL 3.2 source
> (`research/gnucobol-3.2/`) and the Rust port (`crates/gnucobol-rs/src/`) -- for SPECIFIC, code-cited
> divergences (real function names, real `.rs` files, real line numbers). The consolidated findings are a
> committed snapshot (`xtask/src/data/porting_gaps.json`); this doc is generated from it and
> freshness-gated. Regenerate with `cargo run -p xtask -- gap-analysis generate`.
";

const DOCTRINE: &str = "\
## Doctrine -- a gap is not a defect

The port models **observable byte behavior** on the pinned oracle (x86-64, `C.UTF-8` locale, the default
GnuCOBOL dialect, the standard non-experimental libcob build) -- *not* C struct layout -- and explicitly
declares every OS-mutating leaf a boundary (`dlopen`, `sigaction`, `exit`, `system`, `fcntl`, Berkeley DB).
So a large share of these gaps are **faithful-under-oracle** (they diverge only off the pinned
locale/dialect/build) or **admitted-UB** (the C itself is undefined). Nothing is silently omitted: a
faithful no-op, an unreproduced abort, and a genuine value divergence are *all* recorded here. The
`#![forbid(unsafe_code)]` discipline is itself the source of several gaps (no raw pointer deref, no raw fd,
no in-process dynamic loading) -- each is noted where it bites.

**Severity:** `high` = oracle-observable on a real program · `medium` = observable under a stated trigger
(a dialect, a non-C locale, an error path) · `low` = narrow or faithful-but-surprising · `latent` = no
oracle-observable divergence today.
";

fn sev_rank(s: &str) -> u8 {
    match s {
        "high" => 0,
        "medium" => 1,
        "low" => 2,
        _ => 3, // latent / unknown
    }
}

fn build() -> String {
    let m: Value = serde_json::from_str(GAPS).unwrap_or(Value::Null);
    let gaps = m["gaps"].as_array().cloned().unwrap_or_default();
    let panels = m["panels"].as_array().cloned().unwrap_or_default();
    let mut out = String::from(HEADER);

    // ---- summary counts ----
    let mut by_sev: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    let mut by_panel: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    for g in &gaps {
        *by_sev.entry(g["severity"].as_str().unwrap_or("?").to_string()).or_default() += 1;
        *by_panel.entry(g["panel"].as_str().unwrap_or("?").to_string()).or_default() += 1;
    }
    let is_fixed = |g: &Value| g.get("status").and_then(|s| s.as_str()) == Some("fixed");
    let fixed_n = gaps.iter().filter(|g| is_fixed(g)).count();
    let total = gaps.len();
    // open-severity counts EXCLUDE gaps already closed (status: fixed).
    let sev_open = |s: &str| gaps.iter().filter(|g| !is_fixed(g) && g["severity"].as_str() == Some(s)).count();
    let high = sev_open("high");
    let medium = sev_open("medium");
    let low = sev_open("low");
    let latent = sev_open("latent");
    let _ = &by_sev;

    out.push_str(&format!(
        "## Summary -- {total} gaps catalogued across 5 panels ({fixed_n} fixed, {open} open)\n\n\
         | severity | open | meaning |\n|---|---:|---|\n\
         | **high** | {high} | oracle-observable on a real program -- the actionable head of the list |\n\
         | **medium** | {medium} | observable under a stated trigger (a dialect / non-C locale / error path) |\n\
         | **low** | {low} | narrow, or faithful-but-surprising |\n\
         | **latent** | {latent} | no oracle-observable divergence today (admitted UB / capacity bound / faithful boundary) |\n\
         | **fixed** | {fixed_n} | closed + oracle/unit-verified (see the per-gap FIXED note) |\n\n",
        open = total - fixed_n,
    ));

    out.push_str("| panel | scope | gaps |\n|---|---|---:|\n");
    for p in &panels {
        let key = p["key"].as_str().unwrap_or("");
        out.push_str(&format!(
            "| **{}** | {} | {} |\n",
            p["title"].as_str().unwrap_or(""),
            p["scope"].as_str().unwrap_or(""),
            by_panel.get(key).copied().unwrap_or(0),
        ));
    }
    out.push('\n');
    out.push_str(DOCTRINE);
    out.push('\n');

    // ---- the actionable head: all high-severity gaps in one table ----
    out.push_str("## The actionable head -- every `high`-severity gap\n\n");
    out.push_str("These diverge in observable byte output on a real program (no exotic trigger). They are the parity TODO list.\n\n");
    out.push_str("| # | gap | panel | the divergence |\n|---:|---|---|---|\n");
    let mut hi_n = 0;
    for g in &gaps {
        if g["severity"].as_str() == Some("high") && !is_fixed(g) {
            hi_n += 1;
            out.push_str(&format!(
                "| {hi_n} | **{}** | {} | {} |\n",
                g["title"].as_str().unwrap_or(""),
                g["panel"].as_str().unwrap_or(""),
                oneline(g["diff"].as_str().unwrap_or("")),
            ));
        }
    }
    out.push('\n');

    // ---- full per-panel diff ledger ----
    out.push_str("## Full gap ledger (every gap, as a diff)\n\n");
    for p in &panels {
        let key = p["key"].as_str().unwrap_or("");
        let title = p["title"].as_str().unwrap_or("");
        let mut items: Vec<&Value> = gaps.iter().filter(|g| g["panel"].as_str() == Some(key)).collect();
        // sort by severity (high first), then by id, for stable + readable ordering.
        items.sort_by(|a, b| {
            sev_rank(a["severity"].as_str().unwrap_or(""))
                .cmp(&sev_rank(b["severity"].as_str().unwrap_or("")))
                .then_with(|| a["id"].as_str().unwrap_or("").cmp(b["id"].as_str().unwrap_or("")))
        });
        out.push_str(&format!("### Panel: {title} ({} gaps)\n\n", items.len()));
        out.push_str(&format!("> Scope: {}\n\n", p["scope"].as_str().unwrap_or("")));
        for g in items {
            out.push_str(&format!(
                "#### `{}` -- {}  \n",
                g["id"].as_str().unwrap_or(""),
                g["title"].as_str().unwrap_or(""),
            ));
            let status = if is_fixed(g) { " &nbsp;·&nbsp; **status: ✓ FIXED**" } else { "" };
            out.push_str(&format!(
                "**severity:** {} &nbsp;·&nbsp; **observable:** {}{status}\n\n",
                g["severity"].as_str().unwrap_or(""),
                g["observable"].as_str().unwrap_or(""),
            ));
            // the diff: C vs Rust vs divergence.
            out.push_str(&format!("- **GnuCOBOL 3.2 (C):** {}\n", g["c"].as_str().unwrap_or("")));
            out.push_str(&format!("- **gnucobol-rs (Rust):** {}\n", g["rust"].as_str().unwrap_or("")));
            out.push_str(&format!("- **Diff:** {}\n", g["diff"].as_str().unwrap_or("")));
            out.push_str(&format!("- **Evidence / plan:** {}\n\n", g["plan"].as_str().unwrap_or("")));
        }
    }

    // ---- provenance ----
    out.push_str("## Provenance + method\n\n");
    out.push_str(&format!("{}\n\n", m["provenance"].as_str().unwrap_or("")));
    out.push_str(&format!("{}\n\n", m["doctrine"].as_str().unwrap_or("")));
    out.push_str(
        "_Generated from `xtask/src/data/porting_gaps.json` (a committed snapshot of the five-panel \
         forensic audit). Regenerate with `cargo run -p xtask -- gap-analysis generate`; the doc-refresh \
         gate (`lab/check-docs.sh`) fails on drift. To add a gap, edit the JSON and regenerate -- never \
         edit this file by hand._\n",
    );
    out
}

/// Collapse a multi-sentence diff to a single readable table cell (first sentence, escaped pipes).
fn oneline(s: &str) -> String {
    let first = s.split(". ").next().unwrap_or(s);
    first.replace('|', "\\|").trim_end_matches('.').to_string()
}

pub fn run(cmd: &str, root: &str) -> i32 {
    let path = Path::new(root).join("GAP-ANALYSIS.md");
    let text = build();
    match cmd {
        "generate" => {
            if std::fs::write(&path, &text).is_err() {
                eprintln!("gap-analysis: failed to write {}", path.display());
                return 2;
            }
            println!("GAP-ANALYSIS.md generated");
            0
        }
        "check" => {
            let committed = std::fs::read_to_string(&path).unwrap_or_default();
            if committed != text {
                eprintln!("{} STALE: != `xtask gap-analysis generate`. Re-run it.", path.display());
                return 2;
            }
            println!("GAP-ANALYSIS: fresh (regeneration-equal)");
            0
        }
        _ => {
            eprintln!("usage: xtask gap-analysis <generate|check>");
            2
        }
    }
}
