//! PORTING-LADDER — the forensic-port hierarchy (generated from the claim-ladder + coverage map).
//! Faithful Rust port of the former lab/ladder/run.py.
use serde_json::{json, Value};
use std::path::Path;

const LEVELS: [(i64, &str, &str); 8] = [
    (0, "refused subsystem", "out of the data-evidence lane; refused with negative capabilities, never guessed"),
    (1, "observed atlas", "behavior is recorded as observed evidence (a sweep), not a pure-kernel implementation"),
    (2, "byte-equivalent helper", "a pure Rust function reproduces a storage/field/representation byte result"),
    (3, "statement byte court", "a Procedure-Division statement's receiver bytes are reproduced byte-for-byte"),
    (4, "file/runtime-status court", "file/runtime status observation bound to declared conditions"),
    (5, "control-flow fragment", "control-flow surface OBSERVED as an atlas; execution is not claimed"),
    (6, "program-execution slice", "executing a bounded control-flow fragment over the sealed primitives"),
    (7, "compiler/runtime replacement", "NOT CLAIMED — gnucobol-rs is a compatibility court, not a compiler"),
];

fn place() -> Vec<(i64, &'static str)> {
    let l2 = ["GNURUST.2","GNURUST.3","GNURUST.4","GNURUST.5","GNURUST.6","GNURUST.8","GNURUST.9","GNURUST.10","GNURUST.11","GNURUST.CLASS.1","GNURUST.INTRINSIC.LENGTH.1","GNURUST.INTRINSIC.NUMVAL.1","GNURUST.INTRINSIC.NUMVAL-C.1","GNURUST.INTRINSIC.MOD-REM.1","GNURUST.INTRINSIC.INTEGER.1","GNURUST.INTRINSIC.CASE.1","GNURUST.INTRINSIC.ORD-CHAR.1","GNURUST.INTRINSIC.DATE.1","GNURUST.14","GNURUST.15","GNURUST.16","GNURUST.16C","GNURUST.17","GNURUST.18","GNURUST.INDEX.1","GNURUST.LOGICAL.1","GNURUST.FLOAT.1","GNURUST.NUMCMP.1"];
    let l3 = ["GNURUST.7","GNURUST.13","GNURUST.19","GNURUST.REMAINDER.1","GNURUST.ROUND.1","GNURUST.BIGNUM.1","GNURUST.INTPOW.1","GNURUST.FILE.SEQUENTIAL.1","GNURUST.FILE.WRITE.1","GNURUST.FILE.REWRITE.1","GNURUST.FILEIO.LINESEQ.1","GNURUST.12","GNURUST.12B","GNURUST.INITIALIZE.1","GNURUST.INSPECT.1","GNURUST.REFMOD.1","GNURUST.STRING.UNSTRING.1","GNURUST.ACCEPT.DISPLAY.1","GNURUST.ACCEPT.DISPLAY.2","GNURUST.SIZE.ERROR.1"];
    let l1 = ["SIZE.ERROR.ATLAS.1","GNURUST.INTRINSIC.ATLAS.1","GNURUST.CALL.EXTENSION.ATLAS.1","GNURUST.INDEXED.FILE.ATLAS.1","GNURUST.SORT.MERGE.ATLAS.1","GNURUST.RELATIVE.FILE.ATLAS.1","GNURUST.DIALECT.RUNTIME.ATLAS.1","GNURUST.DIRECTIVE.VARIANCE.ATLAS.1","GNURUST.DECLARATIVES.ATLAS.1","GNURUST.CALL.LAYOUT.ATLAS.1","GNURUST.VALUE.NEGZERO.EDGE.1"];
    let l4 = ["GNURUST.FILE.STATUS.1"];
    let l5 = ["GNURUST.PROCEDURE.FLOW.ATLAS.1"];
    let l6 = ["GNURUST.IF.EVALUATE.SLICE.1","GNURUST.IF.NUMERIC.SLICE.1","GNURUST.PERFORM.SLICE.1","GNURUST.TABLE.PERFORM.SLICE.1","GNURUST.SEARCH.TABLE.1","GNURUST.SUBSCRIPT.1","GNURUST.ODO.1","GNURUST.FILE.FLOW.SLICE.1","GNURUST.FILE.FILTER.SLICE.1"];
    let mut v = Vec::new();
    for c in l1 { v.push((1, c)); }
    for c in l2 { v.push((2, c)); }
    for c in l3 { v.push((3, c)); }
    for c in l4 { v.push((4, c)); }
    for c in l5 { v.push((5, c)); }
    for c in l6 { v.push((6, c)); }
    v
}

fn read_json(p: &Path) -> Value {
    std::fs::read_to_string(p).ok().and_then(|s| serde_json::from_str(&s).ok()).unwrap_or(Value::Null)
}

const EXCLUDED: [&str; 7] = ["GNURUST.COVERAGE.1","GNURUST.PUBLIC.CORPUS.1","GNURUST.BUILD.PROFILE.1","GNURUST.PUBLIC.GAP.1","GNURUST.LINEAGE.CORPUS.20M.0","GNURUST.LINEAGE.CORPUS.20M.SMOKE","GNURUST.LINEAGE.CORPUS.20M.1"];

fn gnucobol_courts(root: &str) -> Vec<String> {
    let cl = read_json(&Path::new(root).join("reports/claim-ladder.json"));
    cl["courts"].as_array().map(|a| a.iter().filter_map(|c| c["id"].as_str()).filter(|id| {
        (id.starts_with("GNURUST.") || id.contains("ATLAS")) && !EXCLUDED.contains(id)
    }).map(String::from).collect()).unwrap_or_default()
}

fn build(root: &str) -> Value {
    let cov = read_json(&Path::new(root).join("reports/gnurust-coverage.json"));
    let placed = place();
    let levels: Vec<Value> = LEVELS.iter().map(|(lvl, name, desc)| {
        let mut courts: Vec<&str> = placed.iter().filter(|(l, _)| l == lvl).map(|(_, c)| *c).collect();
        courts.sort();
        json!({"level": lvl, "name": name, "description": desc, "courts": courts})
    }).collect();
    let placed_map: serde_json::Map<String, Value> = placed.iter().map(|(l, c)| (c.to_string(), json!(l))).collect();
    json!({
        "schema": "gnurust-porting-ladder-v1", "court": "PORTING-LADDER",
        "placed": placed_map, "levels": levels,
        "coverage_status_counts": cov["status_counts"],
        "downstream": "KOBOLD (kobold-data-shim) composes the sealed gnucobol-rs courts into a fixed-record migration-evidence layer; it adds no semantics a lower court has not sealed.",
        "non_claims": ["NEG.LADDER.LEVEL_NOT_QUALITY","NEG.LADDER.NOT_A_COMPLETENESS_CLAIM","NEG.LADDER.NO_NEW_TRUTH"]
    })
}

fn render_md(b: &Value) -> String {
    let cc = &b["coverage_status_counts"];
    let mut l = vec![
        "<!-- generated by xtask ladder — do not edit by hand -->".to_string(), String::new(),
        "# PORTING-LADDER — the forensic GnuCOBOL port hierarchy".to_string(), String::new(),
        "> [!IMPORTANT]".to_string(),
        "> Not marketing. A hard map of where each admitted GnuCOBOL surface sits. We are not adding random courts — we are climbing the GnuCOBOL semantic stack, level by level, with oracle receipts.".to_string(),
        String::new(),
        format!("Coverage frontier (from `GNURUST.COVERAGE.1`): **sealed {}**, observed {}, refused {}, **missing {}**.", cc["sealed"], cc["observed"], cc["negative"], cc["missing"]),
        String::new(),
        "| level | meaning | courts |".to_string(), "|:---:|---|---|".to_string(),
    ];
    for r in b["levels"].as_array().unwrap() {
        let courts = r["courts"].as_array().unwrap();
        let cstr = if courts.is_empty() { "—".to_string() } else { courts.iter().map(|c| format!("`{}`", c.as_str().unwrap())).collect::<Vec<_>>().join(", ") };
        l.push(format!("| **{}** | {} — {} | {} |", r["level"], r["name"].as_str().unwrap(), r["description"].as_str().unwrap(), cstr));
    }
    l.extend(["".to_string(), "## Downstream composition".to_string(), String::new(), b["downstream"].as_str().unwrap().to_string(), String::new(),
        "## Non-claims".to_string(),
        "> The level number is **evidence shape, not quality**; the ladder is **not a completeness claim** (see the missing surfaces in `GNURUST.COVERAGE.1`); it creates **no new truth**.".to_string(), String::new()]);
    l.join("\n") + "\n"
}

/// Extract court-id token(s) from a `verify-sealed-courts.sh` run_sweep label. The leading token is the
/// court id; `X/Y` shorthand (e.g. `GNURUST.7/13`) expands to both. Non-court labels (descriptive
/// sub-court sweeps) return empty and are not gated.
fn court_ids_in_label(label: &str) -> Vec<String> {
    let tok = label.split_whitespace().next().unwrap_or("");
    if !tok.contains('.') || !tok.chars().next().map(|c| c.is_ascii_uppercase()).unwrap_or(false) {
        return vec![];
    }
    if let Some(slash) = tok.find('/') {
        let head = &tok[..slash]; // "GNURUST.7"
        let suffix = &tok[slash + 1..]; // "13"
        let prefix = &head[..head.rfind('.').map(|i| i + 1).unwrap_or(0)]; // "GNURUST."
        return vec![head.to_string(), format!("{prefix}{suffix}")];
    }
    vec![tok.to_string()]
}

/// The forensic anti-staleness gate: the claim-ladder is a *source* document, so this proves it still
/// matches machine reality. (1) every court a sweep in `verify-sealed-courts.sh` verifies must be
/// declared in the claim-ladder (no orphan/renamed sweep silently leaving a court unbacked); (2) every
/// court carries the core forensic fields; (3) ids are unique; (4) the declared oracle matches the
/// admission receipt's GnuCOBOL version.
fn forensic_findings(root: &str) -> Vec<String> {
    let mut out = Vec::new();
    let cl = read_json(&Path::new(root).join("reports/claim-ladder.json"));
    let courts = cl["courts"].as_array().cloned().unwrap_or_default();
    let ids: std::collections::HashSet<String> =
        courts.iter().filter_map(|c| c["id"].as_str().map(String::from)).collect();

    // (1) verifier-courts ⊆ ladder-courts
    let verifier = std::fs::read_to_string(Path::new(root).join("lab/verify-sealed-courts.sh")).unwrap_or_default();
    for line in verifier.lines() {
        let line = line.trim_start();
        if !line.starts_with("run_sweep ") {
            continue;
        }
        let Some(open) = line.find('"') else { continue };
        let Some(close) = line[open + 1..].find('"') else { continue };
        let label = &line[open + 1..open + 1 + close];
        for id in court_ids_in_label(label) {
            // EXCLUDED courts are intentionally off-ladder (coverage meta etc.)
            if !ids.contains(&id) && !EXCLUDED.contains(&id.as_str()) {
                out.push(format!("verify-sealed-courts.sh verifies '{id}' but it is not declared in claim-ladder.json (stale)"));
            }
        }
    }

    // (2) + (3) forensic field completeness and unique ids
    let mut seen = std::collections::HashSet::new();
    for c in &courts {
        let id = c["id"].as_str().unwrap_or("<no-id>");
        if !seen.insert(id.to_string()) {
            out.push(format!("duplicate court id '{id}'"));
        }
        for field in ["id", "name", "proven", "oracle", "fixtures", "readiness"] {
            if c[field].is_null() {
                out.push(format!("court '{id}' is missing forensic field '{field}'"));
            }
        }
    }

    // (4) declared oracle matches the admitted GnuCOBOL version
    let oracle = cl["oracle"].as_str().unwrap_or("");
    if !oracle.contains("3.2") {
        out.push(format!("claim-ladder oracle '{oracle}' does not name the admitted GnuCOBOL 3.2 build"));
    }
    out
}

pub fn run(cmd: &str, root: &str) -> i32 {
    match cmd {
        "generate" => {
            let b = build(root);
            let _ = std::fs::write(Path::new(root).join("reports/porting-ladder.json"), serde_json::to_vec_pretty(&b).unwrap_or_default());
            let _ = std::fs::write(Path::new(root).join("PORTING-LADDER.md"), render_md(&b));
            println!("PORTING-LADDER.md generated");
            0
        }
        "check" => {
            let md_path = Path::new(root).join("PORTING-LADDER.md");
            if !md_path.exists() {
                println!("GATE: PORTING-LADDER.md missing");
                return 1;
            }
            let fresh = build(root);
            let mut bad = 0;
            let placed: std::collections::HashSet<String> = fresh["placed"].as_object().unwrap().keys().cloned().collect();
            let allc: std::collections::HashSet<String> = gnucobol_courts(root).into_iter().collect();
            let mut unplaced: Vec<&String> = allc.difference(&placed).collect();
            unplaced.sort();
            for c in unplaced {
                println!("GATE: court {c} is not placed on the porting ladder");
                bad += 1;
            }
            let mut extra: Vec<&String> = placed.difference(&allc).collect();
            extra.sort();
            for c in extra {
                println!("GATE: ladder places {c} which is not a claim-ladder court");
                bad += 1;
            }
            if std::fs::read_to_string(&md_path).unwrap_or_default() != render_md(&fresh) {
                println!("GATE: PORTING-LADDER.md != regenerated");
                bad += 1;
            }
            // --- forensic anti-staleness gate: the claim-ladder must match reality ---
            for f in forensic_findings(root) {
                println!("GATE: {f}");
                bad += 1;
            }
            if bad > 0 {
                println!("!! {bad} PORTING-LADDER finding(s)");
                return 1;
            }
            println!("PORTING-LADDER: {} courts placed across {} levels; fresh", placed.len(), LEVELS.len());
            0
        }
        _ => {
            eprintln!("usage: ladder generate|check");
            2
        }
    }
}
