//! Generates `portcourt.toml` -- the C->Rust port-evidence court declaration -- from the committed parity
//! view (`reports/port-index/parity-detailed.json`) and the coverage-surface court map
//! (`coverage_surfaces.json`). Previously hand-maintained; now generated so the per-file `complete`/`partial`
//! claim and its backing `requires` courts can never drift from the actual port state. `check` regenerates
//! and diffs (anti-staleness; wired into the doc-refresh gate).
use serde_json::Value;
use std::path::Path;

const SURFACES_JSON: &str = include_str!("coverage_surfaces.json");

const HEADER: &str = "\
# portcourt -- the C->Rust port evidence court for gnucobol-rs.
#
# GENERATED by `cargo run -p xtask -- portcourt generate` -- DO NOT EDIT BY HAND.
# Source of truth: reports/port-index/parity-detailed.json (per-file ported/missing/doc-only) +
# xtask/src/coverage_surfaces.json (the sealed court per surface). `portcourt check portcourt.toml` fails
# the build if a `complete` module has any missing / compiled-doc-only function, or a `requires` court that
# is not sealed -- closure math: you cannot claim more than the evidence proves.
#
# Run:  cargo run --manifest-path ../portcourt/Cargo.toml -- check portcourt.toml
";

fn read_json(p: &Path) -> Value {
    std::fs::read_to_string(p).ok().and_then(|s| serde_json::from_str(&s).ok()).unwrap_or(Value::Null)
}

/// The sealed courts backing each libcob file, from the coverage surfaces whose `source_modules` name that
/// file. Returns a map `file.c -> sorted unique court ids` (only `sealed` surfaces contribute).
fn file_courts(file: &str) -> Vec<String> {
    let table: Vec<Value> = serde_json::from_str(SURFACES_JSON).unwrap_or_default();
    let module = format!("libcob/{file}");
    let mut courts: Vec<String> = Vec::new();
    for s in &table {
        let names: Vec<&str> = s["source_modules"].as_array().map(|a| a.iter().filter_map(|m| m.as_str()).collect()).unwrap_or_default();
        if !names.contains(&module.as_str()) {
            continue;
        }
        if let Some(cs) = s["courts"].as_array() {
            for c in cs {
                if let Some(id) = c.as_str() {
                    courts.push(id.to_string());
                }
            }
        }
    }
    courts.sort();
    courts.dedup();
    courts
}

/// Build the canonical `portcourt.toml` text from the parity + surface data.
fn build(root: &str) -> String {
    let parity = read_json(&Path::new(root).join("reports/port-index/parity-detailed.json"));
    let files = parity.as_array().cloned().unwrap_or_default();
    let mut out = String::from(HEADER);
    out.push('\n');
    out.push_str("parity = \"reports/port-index/parity-detailed.json\"\n");
    out.push_str("courts = \"reports/claim-ladder.json\"\n\n");

    for f in &files {
        let name = f["file"].as_str().unwrap_or("");
        if name.is_empty() {
            continue;
        }
        let missing = f["missing"].as_i64().unwrap_or(0);
        // doc-only on COMPILED functions blocks completeness (config_disabled doc-only is benign).
        let compiled_doc_only = f["fns"].as_array().map(|a| {
            a.iter().filter(|fn_| {
                fn_["rust_status"].as_str() == Some("doc_only")
                    && fn_["preprocessor_status"].as_str() == Some("compiled")
            }).count()
        }).unwrap_or(0);
        let complete = missing == 0 && compiled_doc_only == 0;

        out.push_str(&format!("[module.\"{name}\"]\n"));
        if complete {
            out.push_str("claim = \"complete\"\n");
            let courts = file_courts(name);
            if !courts.is_empty() {
                out.push_str("requires = [\n");
                for c in &courts {
                    out.push_str(&format!("  \"{c}\",\n"));
                }
                out.push_str("]\n");
            }
        } else {
            out.push_str("claim = \"partial\"\n");
        }
        out.push('\n');
    }
    // trim the trailing blank line to a single newline
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

pub fn run(cmd: &str, root: &str) -> i32 {
    let text = build(root);
    let path = Path::new(root).join("portcourt.toml");
    match cmd {
        "generate" => {
            if std::fs::write(&path, &text).is_err() {
                eprintln!("portcourt: failed to write {}", path.display());
                return 2;
            }
            println!("portcourt.toml generated ({} modules)", text.matches("[module.").count());
            0
        }
        "check" => {
            let committed = std::fs::read_to_string(&path).unwrap_or_default();
            if committed == text {
                println!("portcourt.toml: fresh (regeneration-equal, {} modules)", text.matches("[module.").count());
                0
            } else {
                eprintln!("portcourt.toml STALE: != `xtask portcourt generate`. Re-run it.");
                2
            }
        }
        _ => {
            eprintln!("usage: xtask portcourt <generate|check>");
            2
        }
    }
}
