//! TRUST.4 lossless authority migration. Port of lab/trust4/migrate_reports.py. The guard runs `check`
//! (no legacy static report left in reports/, manifest intact, replacements exist, front-door clean).
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

fn reports(root: &str) -> PathBuf { Path::new(root).join("reports") }
fn legacy(root: &str) -> PathBuf { Path::new(root).join("research/legacyreports") }
fn sha_b(b: &[u8]) -> String { let mut s = String::new(); for x in Sha256::digest(b) { s.push_str(&format!("{x:02x}")); } s }

fn campaign_of(txt: &str) -> Option<String> {
    txt.lines().find_map(|l| l.strip_prefix("campaign:").map(|v| v.trim().to_string()))
}
fn court_of(path: &str, txt: &str) -> Option<String> {
    if let Some(c) = campaign_of(txt) { return Some(c); }
    let base = Path::new(path).file_name().and_then(|n| n.to_str()).unwrap_or("");
    if base.contains("DECIMAL-1") { return Some("GNURUST.2".into()); }
    let stem = base.strip_suffix(".md")?;
    let tail = &stem[stem.rfind('-')? + 1..];
    if !tail.is_empty() && tail.chars().all(|c| c.is_ascii_digit()) { Some(format!("GNURUST.{tail}")) } else { None }
}

const KEEP: [&str; 3] = ["README.md", "claim-ladder.json", "negative-capabilities.json"];

fn classify(root: &str) -> Vec<Value> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(reports(root)).map(|rd| rd.flatten().map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "md" || x == "json").unwrap_or(false)).collect()).unwrap_or_default();
    files.sort();
    let mut rows = Vec::new();
    for f in files {
        let name = f.file_name().and_then(|n| n.to_str()).unwrap_or("").to_string();
        if KEEP.contains(&name.as_str()) {
            rows.push(json!({"path": format!("reports/{name}"), "kind": "index_or_generated", "current_authority": true, "replacement_required": false, "replacement_path": Value::Null, "move_allowed": false, "classification": "generated_or_index_keep_in_place"}));
            continue;
        }
        let txt = std::fs::read_to_string(&f).unwrap_or_default();
        let camp = court_of(&format!("reports/{name}"), &txt);
        if name.starts_with("RECEIPT-") && camp.is_some() {
            let camp = camp.unwrap();
            let casefile = format!("reports/casefiles/{camp}/casefile.json");
            let exists = Path::new(root).join(&casefile).exists();
            rows.push(json!({"path": format!("reports/{name}"), "kind": "court-receipt", "campaign": camp, "current_authority": false, "replacement_required": true, "replacement_path": if exists { json!(casefile) } else { Value::Null }, "move_allowed": exists, "classification": "legacy_static_superseded_by_casefile"}));
        } else if name == "negative-claims.md" {
            let rep = "reports/negative-capabilities.json";
            rows.push(json!({"path": format!("reports/{name}"), "kind": "negative-claims", "current_authority": false, "replacement_required": true, "replacement_path": rep, "move_allowed": Path::new(root).join(rep).exists(), "classification": "legacy_static_superseded_by_registry"}));
        } else {
            rows.push(json!({"path": format!("reports/{name}"), "kind": "research_doc", "current_authority": false, "replacement_required": false, "replacement_path": Value::Null, "move_allowed": false, "classification": "historical_reference_keep_in_place_non_authoritative"}));
        }
    }
    rows
}

fn inventory(root: &str) -> Vec<Value> {
    let rows = classify(root);
    let dir = reports(root).join("trust4");
    let _ = std::fs::create_dir_all(&dir);
    let out = json!({"schema": "trust4-report-inventory-v1", "doctrine": "No report is authoritative unless generated. Legacy static reports move to research/legacyreports/ only after an information-superset casefile exists; nothing is deleted.", "count": rows.len(), "reports": rows});
    let _ = std::fs::write(dir.join("report-inventory.json"), serde_json::to_vec_pretty(&out).unwrap_or_default());
    let mut lines = vec!["# TRUST.4 report inventory\n".to_string(), "Generated by `xtask trust4 inventory`. Do not edit by hand.\n".to_string(), "| report | kind | classification | replacement | move allowed |".to_string(), "|---|---|---|---|---|".to_string()];
    for r in &rows {
        lines.push(format!("| `{}` | {} | {} | {} | {} |", r["path"].as_str().unwrap(), r["kind"].as_str().unwrap(), r["classification"].as_str().unwrap(), r["replacement_path"].as_str().unwrap_or("—"), r["move_allowed"]));
    }
    let _ = std::fs::write(dir.join("report-inventory.md"), lines.join("\n") + "\n");
    rows
}

pub fn run(cmd: &str, root: &str) -> i32 {
    match cmd {
        "inventory" => {
            let rows = inventory(root);
            println!("inventory: {} reports ({} movable)", rows.len(), rows.iter().filter(|r| r["move_allowed"].as_bool().unwrap_or(false)).count());
            0
        }
        "check" => {
            let mut bad = 0;
            let rows = classify(root);
            for r in &rows {
                let kind = r["kind"].as_str().unwrap_or("");
                if (kind == "court-receipt" || kind == "negative-claims") && Path::new(root).join(r["path"].as_str().unwrap()).exists() {
                    println!("GATE: legacy static report still in reports/ (must move): {}", r["path"].as_str().unwrap());
                    bad += 1;
                }
            }
            let mf = legacy(root).join("MANIFEST.json");
            let mut moved_names: Vec<String> = Vec::new();
            if mf.exists() {
                let man: Value = serde_json::from_str(&std::fs::read_to_string(&mf).unwrap_or_default()).unwrap_or(Value::Null);
                if let Some(moved) = man["moved"].as_array() {
                    for e in moved {
                        moved_names.push(Path::new(e["legacy_path"].as_str().unwrap_or("")).file_name().and_then(|n| n.to_str()).unwrap_or("").to_string());
                        let np = Path::new(root).join(e["new_path"].as_str().unwrap_or(""));
                        if !np.exists() { println!("GATE: moved file missing at {}", e["new_path"].as_str().unwrap_or("")); bad += 1; continue; }
                        if sha_b(&std::fs::read(&np).unwrap_or_default()) != e["legacy_sha256"].as_str().unwrap_or("") { println!("GATE: {} sha256 != manifest", e["new_path"].as_str().unwrap_or("")); bad += 1; }
                        let rep = e["replacement_casefile"].as_str();
                        if rep.is_none() || !Path::new(root).join(rep.unwrap()).exists() { println!("GATE: {} moved without an existing replacement", e["legacy_path"].as_str().unwrap_or("")); bad += 1; }
                    }
                }
            }
            for doc in ["README.md", "STATUS.md"] {
                let p = Path::new(root).join(doc);
                if p.exists() {
                    let t = std::fs::read_to_string(&p).unwrap_or_default();
                    for nm in &moved_names {
                        if t.contains(&format!("reports/{nm}")) { println!("GATE: {doc} still links to moved legacy report reports/{nm}"); bad += 1; }
                    }
                }
            }
            if bad > 0 { println!("!! {bad} TRUST.4 migration gate failure(s)"); return 1; }
            println!("TRUST.4 migration: no legacy static report in reports/, manifest intact, replacements exist, front-door clean");
            0
        }
        _ => { eprintln!("usage: trust4 inventory|check  (migrate is a manual op: see git history)"); 2 }
    }
}
