//! Wrapper-option unsupported census (GNURUST.GNUCOBOL-TESTSUITE evidence).
//!
//! The machine ledger `unsupported-option-census.json` (v2, 180 rows) is current; its Markdown
//! sibling was stale (generated once at commit 8d8c499e8 from an intermediate pass). This module
//! regenerates the Markdown from the committed JSON and enforces reconciliation invariants
//! against the machine ledger (`test-inventory.json`):
//!   - census rows == inventory rows whose primary classification is WRAPPER_OPTION_UNSUPPORTED
//!   - census test_ids are unique (no duplicate step identities)
//!   - token counts sum to the row count
//!   - the census total matches the summary first-failure WRAPPER_OPTION_UNSUPPORTED count

use serde_json::Value;
use std::collections::BTreeMap;
use std::path::Path;

pub const OPTION_CENSUS_SCHEMA: &str = "gnurust-gnucobol-testsuite-unsupported-option-census-v2";

fn csv_escape(s: &str) -> String {
    if s.contains(',') || s.contains('"') || s.contains('\n') {
        format!("\"{}\"", s.replace('"', "\"\""))
    } else {
        s.to_string()
    }
}

fn render_md(census: &Value) -> String {
    let total = census["wrapper_option_unsupported_tests"]
        .as_u64()
        .unwrap_or(0);
    let mut md = String::new();
    md.push_str(&format!(
        "# GnuCOBOL testsuite — wrapper-option unsupported census\n\n\
         **{total} first-failure groups** whose primary classification is \
         `WRAPPER_OPTION_UNSUPPORTED`, decomposed by the first unsupported option token in the \
         candidate invocation. Native-code modes and unmodeled flags are rejected honestly (never \
         silently ignored); tests that later require native artifacts retain a typed boundary. \
         Counting unit: **first_failure_group**.\n\n"
    ));
    md.push_str("## Tokens\n\n");
    let mut tokens: Vec<(&str, u64)> = census["tokens"]
        .as_object()
        .map(|m| {
            m.iter()
                .map(|(k, v)| (k.as_str(), v.as_u64().unwrap_or(0)))
                .collect()
        })
        .unwrap_or_default();
    tokens.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(b.0)));
    for (t, n) in tokens {
        md.push_str(&format!("- {n}: `{}`\n", csv_escape(t)));
    }
    md.push_str("\n## Per-test ledger (counting_unit = first_failure_group)\n\n");
    md.push_str("| id | title | group | token | reason |\n|---|---|---|---|---|\n");
    if let Some(arr) = census["tests"].as_array() {
        for r in arr {
            md.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                r["test_id"].as_str().unwrap_or(""),
                csv_escape(r["title"].as_str().unwrap_or("")),
                csv_escape(r["group"].as_str().unwrap_or("")),
                csv_escape(r["token"].as_str().unwrap_or("")),
                csv_escape(r["reason"].as_str().unwrap_or("")),
            ));
        }
    }
    md.push_str(&format!(
        "\n{total} rows; generated by `gnucobol-rs-testsuite option-census generate` — do not edit by hand.\n"
    ));
    md
}

/// Verify the committed option census against the machine ledger. Returns (notes, problems).
pub fn verify_committed(root: &Path) -> Result<(Vec<String>, Vec<String>), String> {
    let rep = root.join("reports/gnucobol-testsuite");
    let census_path = rep.join("unsupported-option-census.json");
    let inv_path = rep.join("test-inventory.json");
    let sum_path = rep.join("summary.json");
    let mut notes = Vec::new();
    let mut problems = Vec::new();

    let census: Value = serde_json::from_str(
        &std::fs::read_to_string(&census_path)
            .map_err(|e| format!("option census unreadable: {e}"))?,
    )
    .map_err(|e| format!("option census malformed: {e}"))?;
    let inv: Value = serde_json::from_str(
        &std::fs::read_to_string(&inv_path).map_err(|e| format!("inventory unreadable: {e}"))?,
    )
    .map_err(|e| format!("inventory malformed: {e}"))?;

    let census_ids: BTreeMap<String, Value> = census["tests"]
        .as_array()
        .map(|a| {
            a.iter()
                .map(|t| (t["test_id"].as_str().unwrap_or("").to_string(), t.clone()))
                .collect()
        })
        .unwrap_or_default();
    let inv_wrapper: Vec<String> = inv["tests"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter(|t| {
                    t["primary_classification"].as_str() == Some("WRAPPER_OPTION_UNSUPPORTED")
                })
                .filter_map(|t| t["test_id"].as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    if census_ids.len() != inv_wrapper.len() {
        problems.push(format!(
            "option census rows {} != inventory WRAPPER_OPTION_UNSUPPORTED groups {}",
            census_ids.len(),
            inv_wrapper.len()
        ));
    }
    for id in &inv_wrapper {
        if !census_ids.contains_key(id) {
            problems.push(format!("option census missing inventory group {id}"));
        }
    }
    for id in census_ids.keys() {
        if !inv_wrapper.contains(id) {
            problems.push(format!("option census has non-wrapper group {id}"));
        }
    }

    let token_total: u64 = census["tokens"]
        .as_object()
        .map(|m| m.values().map(|v| v.as_u64().unwrap_or(0)).sum())
        .unwrap_or(0);
    if token_total != census_ids.len() as u64 {
        problems.push(format!(
            "option census token total {token_total} != row count {}",
            census_ids.len()
        ));
    }

    if let Ok(raw) = std::fs::read_to_string(&sum_path) {
        if let Ok(s) = serde_json::from_str::<Value>(&raw) {
            let ff = s["summary"]["first_failure"]["WRAPPER_OPTION_UNSUPPORTED"]
                .as_u64()
                .unwrap_or(0) as usize;
            if ff != census_ids.len() {
                problems.push(format!(
                    "option census rows {} != summary first-failure WRAPPER_OPTION_UNSUPPORTED {ff}",
                    census_ids.len()
                ));
            }
        }
    }

    // Freshness: regenerate the Markdown and diff.
    let fresh_md = render_md(&census);
    let committed_md = std::fs::read(rep.join("unsupported-option-census.md")).unwrap_or_default();
    if committed_md != fresh_md.as_bytes() {
        notes.push(
            "STALE: reports/gnucobol-testsuite/unsupported-option-census.md != regeneration".into(),
        );
    }
    Ok((notes, problems))
}

/// Regenerate the option census Markdown from the committed JSON (after invariants pass).
pub fn generate(root: &Path) -> Result<(), String> {
    let (notes, problems) = verify_committed(root)?;
    if !problems.is_empty() {
        return Err(format!(
            "option census reconciliation failed: {}",
            problems.join("; ")
        ));
    }
    let rep = root.join("reports/gnucobol-testsuite");
    let census: Value = serde_json::from_str(
        &std::fs::read_to_string(rep.join("unsupported-option-census.json"))
            .map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;
    std::fs::write(rep.join("unsupported-option-census.md"), render_md(&census))
        .map_err(|e| format!("write failed: {e}"))?;
    let _ = notes;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn committed_option_census_reconciles_with_inventory() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let census = root.join("reports/gnucobol-testsuite/unsupported-option-census.json");
        let inv = root.join("reports/gnucobol-testsuite/test-inventory.json");
        if !census.exists() || !inv.exists() {
            return;
        }
        let (notes, problems) = verify_committed(&root).unwrap();
        assert!(problems.is_empty(), "problems: {problems:?}");
        // The committed Markdown is regenerated by this campaign; until then the JSON must at
        // least reconcile. The freshness note is expected to be cleared by `option-census generate`.
        let _ = notes;
    }
}
